### ISSUE TITLE
yaml_cpp exceptions issue on x86

### ISSUE THREAD

**Issue by jackburton79** [haikuports/haikuports#9792] opened 2023-11-25 19:00 UTC
On beta4 32 bit (Hybrid), when opening a non existing file, Yaml raises exceptions which can't be catched.

The following code exits with abort() (After throwing an uncatched YAML::BadFile exception), while It should exit cleanly (it does, in fact, on x64 master)

`#include <yaml-cpp/yaml.h>

int main()
{
try {
YAML::LoadFile(std::string("foo"));
} catch(...) {
}
`

I'm current.

**Comment by jackburton79** [comment] 2023-11-25 19:01
Obviously you need to use setarch x86 to compile, since yaml_cpp is not available on gcc2

**Comment by waddlesplash** [comment] 2023-11-26 00:56
Same problem documented here: https://github.com/KapiX/Koder/issues/147

**Comment by waddlesplash** [comment] 2023-12-10 04:19
It's been ascertained the problem is due to call frame information differing in GCC 11 vs 13. Why this is so hasn't been determined, nor what the solution is supposed to be...

**Comment by korli** [comment] 2024-06-13 09:19
fixed in 039cb8c4f98a3b2b71e6576e77a851d937cf7fd3

**Closed by korli** 2024-06-13 09:19 UTC
