### ISSUE TITLE
MilkyTracker crashes (Event port write failed: bad port ID) on launch and doesn't built

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#7061] opened 2022-07-19 13:15 UTC
MilkyTracker (1.03.00-1) crashes on launch on Haiku hrev56295, 64bit:

[MilkyTracker-1525-debug-19-07-2022-13-02-35.report.txt](https://github.com/haikuports/haikuports/files/9141303/MilkyTracker-1525-debug-19-07-2022-13-02-35.report.txt)

Tried to re-build, stops with:

```
In file included from /boot/system/develop/tools/lib/gcc/x86_64-unknown-haiku/11.2.0/include/c++/algorithm:74,
                 from src/tracker/SampleEditorControl.cpp:35:
/boot/system/develop/tools/lib/gcc/x86_64-unknown-haiku/11.2.0/include/c++/pstl/glue_algorithm_defs.h:15:10: fatal error: execution_defs.h: No such file or directory
   15 | #include "execution_defs.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

g++ -c -o src/tracker/SampleEditorControl.o -O2 -DMILKYTRACKER -D__HAIKU__  -Isrc/tracker -I./src/compression -I./src/fx -I./src/midi/haiku -I./src/milkyplay -I./src/ppui/osinterface -I./src/ppui/osinterface/posix -I./src/ppui -I./src/ppui/haiku -I./src/tracker/haiku -I- src/tracker/SampleEditorControl.cpp

...failed C++ src/tracker/SampleEditorControl.o ...

BUILD FAILURE:

```

**Comment by diversys** [comment] 2022-07-19 17:03
Dupe of #6488.

**Closed by diversys** 2022-07-19 17:03 UTC
