### ISSUE TITLE
DOSBox: Running nasm inside DOSBox cause a KDL 

### ISSUE THREAD

**Issue by mahiuchun** [haikuports/haikuports#5002] opened 2020-05-22 00:49 UTC
Steps to reproduce:

1. Create a new directory such as `~/dosprogs`
2. Download `nasm` for DOS from https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/dos/nasm-2.14.02-dos.zip
3. Expand and copy `nasm` directory into `~/dosprogs`.
4. Launch DOSBox; type `mount c ~/dosprogs`
5. Give these commands `c:`, `c:\nasm\nasm.exe`

BTW, I have not encountered issues running `nasm` inside DOSBox on other platform.

**Comment by waddlesplash** [comment] 2020-05-22 01:13
Duplicate of https://dev.haiku-os.org/ticket/14711.

**Closed by waddlesplash** 2020-05-22 01:13 UTC
