### ISSUE TITLE
gcc13 defaults to the latest version of dwarf

### ISSUE THREAD

**Issue by nexus6-haiku** [haikuports/haikuports#9261] opened 2023-08-22 08:55 UTC
Unlike gcc11, gcc13 seems to default to dwarf 5 that is incompatible with Debugger.
-gdwarf-3 must be passed manually and works for me.
From the recipe I can see the patch forces gcc to dwarf 2, do we know if version 3 has any issue?

**Comment by davidkaroly** [comment] 2023-08-25 11:33
default dwarf version seems to be 4 which is specified here:
```
void
haiku_override_options (void)
{
  if (!global_options_set.x_dwarf_strict)
    dwarf_strict = 1;
  if (!global_options_set.x_dwarf_version)
    dwarf_version = 4;

  /* PIE does not work on Haiku, but PIC does the right thing for position
   * independant executables. So if asked for PIE, do PIC instead.
   */
  if (flag_pie && !flag_pic)
    flag_pic = flag_pie;
  flag_pie = 0;
}
```

see:
https://github.com/haikuports/haikuports/blob/master/sys-devel/gcc/patches/gcc-13.2.0_2023_08_10.patchset#L5280

**Comment by davidkaroly** [comment] 2023-08-27 15:25
should we try something like this?

```diff
diff --git a/gcc/config/haiku.c b/gcc/config/haiku.c
index af14c02..bdd6f08 100644
--- a/gcc/config/haiku.c
+++ b/gcc/config/haiku.c
@@ -28,7 +28,7 @@ haiku_override_options (void)
   if (!global_options_set.x_dwarf_strict)
     dwarf_strict = 1;
   if (!global_options_set.x_dwarf_version)
-    dwarf_version = 4;
+    dwarf_version = 3;

   /* PIE does not work on Haiku, but PIC does the right thing for position
    * independant executables. So if asked for PIE, do PIC instead.
```

@nielx @waddlesplash

**Comment by nielx** [comment] 2023-08-27 16:07
I think @waddlesplash identified that it is actually not the case that we previously set dwarf version 2, but we have been at dwarf version 4 for a while now. Only it seems that GCC is now using Dwarf version 4 output for lineinfo, and our Debugger does not support that.

I suggest the actual solution is not to downgrade the default dwarf output, but to patch Debugger to support the lineinfo.

**Comment by nielx** [comment] 2023-08-27 16:08
This was on the haiku-commits list: https://www.freelists.org/post/haiku-commits/haiku-hrev57242-srckitsdebuggerdwarf,2

**Comment by davidkaroly** [comment] 2023-08-27 18:10
> I suggest the actual solution is not to downgrade the default dwarf output, but to patch Debugger to support the lineinfo.

yes you're right, that would be a better way forward

**Comment by pulkomandy** [comment] 2023-09-05 19:44
Can this be closed thanks to https://cgit.haiku-os.org/haiku/commit/?h=hrev57248&id=3f2464f759bbb21f49e8abf5bad429ba7d344952 ?

**Comment by waddlesplash** [comment] 2023-09-05 19:45
I don't know about that; last I was seeing, without explicitly specifying `-gdwarf-4`, GCC was still generating version 5 lineinfo.

**Comment by davidkaroly** [comment] 2023-09-05 19:53
> I don't know about that; last I was seeing, without explicitly specifying `-gdwarf-4`, GCC was still generating version 5 lineinfo.

yep that seems to be the case: `gcc -g` generated DWARFv4 debug info with v5 lineinfo, which cannot be parsed by Haiku Debugger. 
`gcc -gdwarf-4` generated DWARFv4 debug info with v4 lineinfo which can be processed by Debugger.

**Comment by nielx** [comment] 2023-09-06 09:28
This smells like a GCC bug, but spending about an hour looking through the code and to be honest, nothing really stands out. There seems to be a global variable, `dwarf_version` which is set to the dwarf version that is either set explicitly, or implicitly. Then the meat seems to be in [`output_line_info()`](https://github.com/haiku/buildtools/blob/f7a513f6367dbb570ba0a71a4bbbfcbc217b0201/gcc/gcc/dwarf2out.cc#L13065), specifically [line 13092](https://github.com/haiku/buildtools/blob/f7a513f6367dbb570ba0a71a4bbbfcbc217b0201/gcc/gcc/dwarf2out.cc#L13092), where `output_dwarf_version()` seems to output 5, even though I assume that other uses of this function would output 4 (like the [`output_compilation_unit_header()`](https://github.com/haiku/buildtools/blob/f7a513f6367dbb570ba0a71a4bbbfcbc217b0201/gcc/gcc/dwarf2out.cc#L11179).

Am I looking at the right code? And if so, does that mean that somewhere during outputting dwarf info the global variable is changed, unless the option was set by command line?

**Comment by korli** [comment] 2023-09-06 11:01
While at here, the code for other OSes was updated to use  `if (!OPTION_SET_P (dwarf_version))` and `if (!OPTION_SET_P (dwarf_strict))`
see https://github.com/gcc-mirror/gcc/commit/00f34291175981393b2a9802ada879e72335dcd0

An alternative like vxworks would be to set DWARF_VERSION_DEFAULT in gcc/gcc/config/haiku.h

**Comment by waddlesplash** [comment] 2023-09-21 02:22
DWARF_VERSION_DEFAULT sounds like the best solution.

**Comment by davidkaroly** [comment] 2023-10-04 18:59
Meanwhile Debugger now should be able to parse v5 line number info, see: [hrev57309](https://cgit.haiku-os.org/haiku/commit/?h=hrev57309&id=006478bfce5d82619a4dab86c8cf54890ea2a525)

**Comment by nielx** [comment] 2023-10-04 19:33
Arguably the better solution anyway ;-)

**Comment by korli** [comment] 2023-10-05 07:03
> Meanwhile Debugger now should be able to parse v5 line number info, see: [hrev57309](https://cgit.haiku-os.org/haiku/commit/?h=hrev57309&id=006478bfce5d82619a4dab86c8cf54890ea2a525)

Albeit only in nightlies... or do you intend to bring this into the beta4 branch?

**Comment by davidkaroly** [comment] 2023-10-05 10:14
> > Meanwhile Debugger now should be able to parse v5 line number info, see: [hrev57309](https://cgit.haiku-os.org/haiku/commit/?h=hrev57309&id=006478bfce5d82619a4dab86c8cf54890ea2a525)
> 
> Albeit only in nightlies... or do you intend to bring this into the beta4 branch?

not sure.

is there a description of the backporting process/policy for the beta maintenance branches? i.e. what kind of backports can be accepted, who makes the decision etc.

**Comment by pulkomandy** [comment] 2023-10-05 10:50
The process is to push some changes to the refs/for/r1beta4 branch on Gerrit and it gets reviewed and merged as usual (someone has to vote +2 and merge, anyone who has commit permissions can do it).

There isn't really a policy except for "don't break things". So, no ABI changes, mainly bugfixes, and usually changes that have been deployed on the nightlies for a few days/weeks to make sure there is no regressions.

And, "Debugger does not show any sourcecode" can be considered a bug, so, we can put it in the bugfix category?

**Comment by korli** [comment] 2023-10-05 10:59
I see 7 commits in src/kits/debugger since r1beta4, they look well concentrated on src/kits/debugger/dwarf. Debugger code isn't affected it seems.

Gerrit lets the user cherry-pick changes for review in the UI.

**Comment by davidkaroly** [comment] 2023-10-16 20:37
The patches for parsing lineinfo v4 have been cherry-picked to r1beta branch. 
Two more patches are open in gerrit, for lineinfo v5.

**Comment by korli** [comment] 2023-12-19 10:09
Can we close this?

**Comment by nexus6-haiku** [comment] 2023-12-19 10:19
Fine from my side

**Closed** 2023-12-19 10:33 UTC
