### ISSUE TITLE
cmake does not know where to find PYTHON_LIBRARY or PYTHON_INCLUDE_DIR

### ISSUE THREAD

**Issue by andrewzx1** [haikuports/haikuports#920] opened 2016-12-10 15:32 UTC
steps to reproduce:
Install cmake
download source for Blender
mkdir build
cd build
ccmake ..

cmake error at
/boot/system/data/cmake/Modules/FindPackageHandleStandardArgs.cmake:148
Could NOT find PythonLibsUnix (missing: PYTHON_LIBRARY PYTHON_INCLUDE_DIR)

**Comment by korli** [comment] 2016-12-13 09:17
Well we define these:
https://github.com/haikuports/haikuports/blob/master/media-gfx/blender/blender-2.76.recipe

and Gentoo does too:
https://gitweb.gentoo.org/repo/gentoo.git/tree/media-gfx/blender/blender-2.78a.ebuild#n150

so I don't know what the issue is.

**Comment by pulkomandy** [comment] 2016-12-13 09:21
Why are we passing these to make? They should be passed to cmake in order to generate the makefile properly?

**Comment by korli** [comment] 2016-12-13 13:06
Is it important what this particular project does with make/cmake? Because I don't see the point.
https://github.com/dfelinto/blender/blob/master/GNUmakefile#L22

**Comment by pulkomandy** [comment] 2016-12-13 13:14
I would ignore this makefile and use cmake directly. This seems to be what gentoo is doing.

See "manual CMake setup" in https://wiki.blender.org/index.php/Dev:Doc/Building_Blender/Linux/Generic_Distro/CMake

I don't know if the "helper" makefile properly forwards the defines to CMake when it runs it.

**Comment by korli** [comment] 2016-12-13 16:07
What do you actually gain from that?
I'm closing this.

**Closed by korli** 2016-12-13 16:07 UTC
