### ISSUE TITLE
port htop

### ISSUE THREAD

**Issue by 1o1o1** [haikuports/haikuports#6641] opened 2022-02-19 19:29 UTC
don't work  :(

![Снимок экрана 2022-02-19 в 21 26 28](https://user-images.githubusercontent.com/46845416/154816080-a2b2f4be-d008-47c5-b46d-4faf954d978e.png)

**Comment by extrowerk** [comment] 2022-02-25 07:54
For reference: https://github.com/haikuports/haikuports/tree/master/sys-process/htop

**Comment by 1o1o1** [comment] 2022-02-25 08:40
can you build for update in pkgman ??

**Comment by extrowerk** [comment] 2022-02-25 09:24
> can you build for update in pkgman ??

It is marked as untested.

**Comment by extrowerk** [comment] 2022-02-25 09:25
Duplicate of https://github.com/haikuports/haikuports/issues/1655

**Closed by extrowerk** 2022-02-25 09:25 UTC
