### ISSUE TITLE
Node.js and NW.js (formely node-webkit) ports

### ISSUE THREAD

**Issue by jalbam** [haikuports/haikuports#767] opened 2016-08-14 01:47 UTC
Hello,

Chromium was already ported to Haiku successfully.

I have been looking around and there seems to be a very old port of Node.js to Haiku although I am not sure whether it works well or not.

Could it be possible to port both Node.js (a newer version) and NW.js projects to Haiku OS? Perhaps using Haikuporter.

That would be great for the Haiku community since NW.js (which is based on Chromium and Node.js) could be used to port many more web-based applications and games that are very common nowadays.

Do you think that is possible?

Thank you very much.

Cheers,
 Joan

**Comment by waddlesplash** [comment] 2016-08-15 13:49
> Chromium was already ported to Haiku successfully.

It was? This is news to me. It sure would be nice to have Chromium, but to my knowledge we only have WebKit.

> I have been looking around and there seems to be a very old port of Node.js to Haiku although I am not sure whether it works well or not.

Where's this? I know there is a (ancient, non-functional) V8 recipe, but I don't think node was ported. Specifically it needs libuv, of which there was recently a half-functioning port.

> Could it be possible to port both Node.js (a newer version) and NW.js projects to Haiku OS? Perhaps using Haikuporter.

I was looking at this at one point, but I don't know if I have the time to go back to it. (Also, it's just "Haiku" not "Haiku OS".)

**Comment by jalbam** [comment] 2016-08-15 14:12
Sorry, I meant WebKit instead of Chromium.

Regarding the Node.js port, I found it here: https://github.com/benjaminoakes/node (but maybe it is still not finished). I think I also found another place but now I cannot find it now.

When I said "OS" it is because that stands for "Operating System". And Haiku is an operating system. By the way, their web site is haiku-os.org

**Comment by fbrosson** [comment] 2016-08-15 14:33
That's OK. Many people think it is "Haiku OS" because the website is haiku-os.org.
The reason why the website is not haiku.org is that that domain name is not available...

Maybe we should put in the "About" page of the website something like **_Although the project's website domain name is haiku-os.org, the official name of the operating system is just Haiku, without the "OS". And the Haiku community likes to use that official name, Haiku._**

**Comment by humdingerb** [comment] 2016-08-15 14:37
It's already in the FAQ. Quite far to the top even... :)
https://www.haiku-os.org/about/faq#top_2

Regards,
Humdinger

--
Did you know:
  If half the Haiku supporters at http://www.goodsearch.com
  made 10 searches a day, we could have a fulltime developer.

**Comment by fbrosson** [comment] 2016-08-15 14:50
Oops, I forgot it was in the FAQ, sorry.
But maybe it should be also added at the bottom of the About page, in a small but bold face, because most visitors start with the About page but do not always read the FAQ, or if they do read the FAQ they skip most of it ;-)

**Comment by waddlesplash** [comment] 2016-08-15 14:50
> Sorry, I meant WebKit instead of Chromium.

WebKit and Chromium have two very different platform abstraction layers; a WebKit port does almost nothing towards a Chromium port. And NW.js uses Chromium, not WebKit.

> Regarding the Node.js port, I found it here: https://github.com/benjaminoakes/node (but maybe it is still not finished). I think I also found another place but I cannot find it now.

That's far too old to be at all useful.

**Comment by jalbam** [comment] 2016-08-16 07:40
So I guess to accomplish the task to port NW.js to Haiku first we would need to port both Chromium and V8/Node.js. Right?

**Comment by waddlesplash** [comment] 2016-08-16 13:39
Yes.

**Comment by pulkomandy** [comment] 2017-01-21 18:12
Duplicate of #107.

**Closed by pulkomandy** 2017-01-21 18:12 UTC
