### ISSUE TITLE
Add recipe for TesseractTranslator

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#1487] opened 2017-07-03 06:24 UTC
https://github.com/threedeyes/TesseractTranslator

**Comment by phoudoin** [comment] 2017-07-03 16:18
I've one ^_^

Issue is libtesseract.so has a dependency on connect() which is unresolved. 
Our tesseract haikuports is broken?

**Comment by phoudoin** [comment] 2017-07-05 09:51
This missing recipe issue is fixed. Could someone close it?

**Comment by korli** [comment] 2017-07-05 11:25
There is some issue with the recipe, let's keep this issue open as a reminder.

**Comment by phoudoin** [comment] 2017-07-05 16:31
The issue is (well, was, when my PR will be merged) in apps-text/tesseract port, not in the translator itself.

**Closed** 2017-07-05 22:09 UTC
Labels: type-enhancement
