### ISSUE TITLE
flex does not provide a 'lex' binary

### ISSUE THREAD

**Issue by ddevault** [haikuports/haikuports#5115] opened 2020-06-14 23:01 UTC
POSIX compliance issue

**Comment by extrowerk** [comment] 2020-06-16 06:00
Do i understand correctly: all it needs just a "lex" symlink to "flex", right?

**Comment by ddevault** [comment] 2020-06-16 12:05
Aye.

**Comment by Begasus** [comment] 2020-09-27 16:31
It's an easy fix, but is there any reason to include this? afaikt using "cmd:flex" seems to be doing ok, if there is a package/source not checking for "flex" and needs "lex" could you point me to it?

**Comment by ddevault** [comment] 2020-09-27 16:32
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/lex.html

**Comment by Begasus** [comment] 2020-09-27 16:43
Already found some ports on repology that links lex to flex, was looking for some example on where it fails to find "lex"

**Comment by ddevault** [comment] 2020-09-27 16:44
I have an example in a private repository. I won't share. If Haiku wishes to be POSIX complaint it will provide a lex binary, that is that.

**Comment by Begasus** [comment] 2020-09-27 17:04
Been checking up on it, the build and linking isn't a problem, seems there are quite some parse errors running the tests with haikuporter for gcc2, wip ...

**Comment by Begasus** [comment] 2020-09-27 18:19
Not sure if you are able to build the changes made in the PR: https://github.com/haikuports/haikuports/pull/5303
Tests are failing there as explained earlier, but other than that it builds and packages fine.
I've uploaded a change to use gcc8 for flex on 32bit, this needs to be confirmed ok and working before any merges

**Comment by ddevault** [comment] 2020-09-27 18:21
Nice work, thanks.

**Comment by Begasus** [comment] 2020-09-29 06:49
@ddevault could you check https://github.com/Begasus/haikuports/commit/90ad57c9635a938c763e8289e1934831aaccaec2 ?
This is a build for flex with gcc8, would be nice to see if it works for your needs too (focused on 32 bit Haiku)

**Comment by Begasus** [comment] 2020-09-29 09:57
Fixed in https://github.com/haikuports/haikuports/pull/5303

**Closed by Begasus** 2020-09-29 09:57 UTC
Labels: type-bug

**Comment by ddevault** [comment] 2020-09-29 15:19
Why was it done in the same commit? Well, whatever. Thanks!

**Comment by Begasus** [comment] 2020-09-29 17:41
> Why was it done in the same commit? Well, whatever. Thanks!

It isn't, gcc8 version hasn't had a PR so far yet (need some testers for that before I file a PR), the merged commit is only for the gcc2 version with the symlink added
