### ISSUE TITLE
Adjust path to .wget-hsts in wget

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#739] opened 2016-07-25 11:06 UTC
Currently wget creates ~/.wget-hsts file. It should probably be moved to ~/config/cache

**Comment by korli** [comment] 2016-07-31 21:24
Sounds like #460, which should already fixed after the update of packages on 21th July. Please check again.

**Comment by Giova84** [comment] 2016-08-11 01:23
I am on Haiku hrev50480 and now the "wget-hsts" file (now without the dot) is present under ~/config/settings

**Comment by pulkomandy** [comment] 2017-01-22 09:13
Duplicate of #460.

**Closed by pulkomandy** 2017-01-22 09:13 UTC
Labels: type-enhancement
