### ISSUE TITLE
pip install hangs forever

### ISSUE THREAD

**Issue by probonopd** [haikuports/haikuports#3993] opened 2019-07-15 13:55 UTC
```
~> pip install zeroconf
Collecting zeroconf
  Downloading https://files.pythonhosted.org/packages/d7/25/8bbdd4857820e0cdc380c7e0c3543dc01a55247a1d831c712571783e74ec/zeroconf-0.23.0.tar.gz
Collecting ifaddr (from zeroconf)
  Downloading https://files.pythonhosted.org/packages/9f/54/d92bda685093ebc70e2057abfa83ef1b3fb0ae2b6357262a3e19dfe96bb8/ifaddr-0.1.6.tar.gz
Collecting typing; python_version < "3.5" (from zeroconf)
  Downloading https://files.pythonhosted.org/packages/79/be/e43ccd1317f483e14de507787322c74092a688707d02fa5f16562270eb63/typing-3.7.4-py2-none-any.whl
Collecting ipaddress (from ifaddr->zeroconf)
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Installing collected packages: ipaddress, ifaddr, typing, zeroconf
  Running setup.py install for ifaddr ... done
  Running setup.py install for zeroconf ... done
Successfully installed ifaddr-0.1.6 ipaddress-1.0.22 typing-3.7.4 zeroconf-0.23.0
```

It does not exit here.

**Comment by probonopd** [comment] 2019-07-15 13:55
Ctrl-C, Ctrl-D gives:

```
Traceback (most recent call last):
  File "/bin/pip", line 11, in <module>
    load_entry_point('pip==9.0.0', 'console_scripts', 'pip')()
  File "/packages/python-2.7.16-3/.self/lib/python2.7/vendor-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/packages/python-2.7.16-3/.self/lib/python2.7/vendor-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/packages/python-2.7.16-3/.self/lib/python2.7/vendor-packages/pip/utils/outdated.py", line 138, in pip_version_check
    state.save(pypi_version, current_time)
  File "/packages/python-2.7.16-3/.self/lib/python2.7/vendor-packages/pip/utils/outdated.py", line 71, in save
    with lockfile.LockFile(self.statefile_path):
  File "/packages/python-2.7.16-3/.self/lib/python2.7/vendor-packages/pip/_vendor/lockfile/__init__.py", line 197, in __enter__
    self.acquire()
  File "/packages/python-2.7.16-3/.self/lib/python2.7/vendor-packages/pip/_vendor/lockfile/linklockfile.py", line 50, in acquire
    time.sleep(timeout is not None and timeout / 10 or 0.1)
KeyboardInterrupt
```

**Comment by pulkomandy** [comment] 2019-07-15 14:08
Duplicate of #3420

**Closed by pulkomandy** 2019-07-15 14:08 UTC
