### ISSUE TITLE
can't start otter or qupzilla anymore

### ISSUE THREAD

**Issue by AlienSoldier2** [haikuports/haikuports#3911] opened 2019-06-08 04:35 UTC
shortly after the latest QT plugin and QT5 update, i was no longer to be able to launch those app on my gcc2 hybrid haiku 32bit.

What happen is that process controller show 100% activity one one core and then this move to another core, then back on the initial one.  The system is taking forever to load anything new from that point, but i am able to shutdown it.

When trying to use process controler to kill the process it say it is empty and "already gone".

Qmplay2 and qbitorrent seem to launch fine still.

**Comment by threedeyes** [comment] 2019-06-08 13:24
1. pkgman update - and try again (qtwebkit package need to be updated)
2. run application from Terminal

**Comment by unspacyar** [comment] 2019-06-08 16:20
Same issue here.  Apparently the problem is the updated Qt5Webkit package.  When try to start Otter from Terminal, I get this:
/boot/system/apps/Otter-Browser> ./Otter-Browser 
runtime_loader: /boot/system/lib/x86/libQt5WebKit.so.5.212.0: Could not resolve symbol '_ZNSs4_Rep20_S_empty_rep_storageE'
resolve symbol "_ZNSs4_Rep20_S_empty_rep_storageE" returned: -2147478780
runtime_loader: /boot/system/lib/x86/libQt5WebKit.so.5.212.0: Troubles relocating: Symbol not found
/boot/system/apps/Otter-Browser> 

Another Qt5 apps apparently works well.

**Comment by extrowerk** [comment] 2019-06-09 21:29
Interestingly in Slayer the PID increments rapidly.

**Comment by threedeyes** [comment] 2019-06-09 22:15
> Interestingly in Slayer the PID increments rapidly.
I think it bug in Tracker. Process relaunched by Tracker. If you kill tracker - it stopped.

**Comment by threedeyes** [comment] 2019-06-09 22:17
> Same issue here. Apparently the problem is the updated Qt5Webkit package. 

what qtwebkit version and revision is installed?

**Comment by AlienSoldier2** [comment] 2019-06-09 22:17
"(qtwebkit package need to be updated)"  That seem to be the problem.  When looking into the latest haikudepot package i see it for x86_64 not far from the Qt5 package but i dont see it when listing for x86_gcc2.  So pkgman update did not added it when i just tried 1 min ago.

**Comment by threedeyes** [comment] 2019-06-09 22:21
hmm.
rebuild qtwebkit for x86_gcc2 failed - https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=2998&viewMode=expanded

**Comment by AlienSoldier2** [comment] 2019-06-10 01:04
I wonder if something is related to the move to gcc8.

**Comment by threedeyes** [comment] 2019-06-10 03:36
> I wonder if something is related to the move to gcc8.

Maybe.
I will try tonight to switch qtwebkit to the annulen version with many fixes and merges with the main webkit branch.

**Comment by Begasus** [comment] 2019-06-10 06:12
Haven't looked through the full log, maybe -Werror is in the way here?

**Comment by threedeyes** [comment] 2019-06-10 22:05
We need apply this patch: https://github.com/annulen/webkit/commit/d754672046770d312a675c8541143d066ff95a49

**Comment by kenmays** [comment] 2019-06-11 17:44
@AlienSoldier2, @unspacyar - Tested. Issue fixed in qtwebkit_x86 -9 on x86_gcc2.

**Comment by AlienSoldier2** [comment] 2019-06-11 18:38
Fine from my side also now :)

**Closed** 2019-06-11 18:38 UTC
