### ISSUE TITLE
Bypass building of unnecessary secondaryArch packages

### ISSUE THREAD

**Issue by cb88** [haikuports/haikuports#3188] opened 2018-10-05 02:01 UTC
Either haikuports recipes need to disable unnecessary builds manually or haikuporter needs to prevent them from being built. As I understand it packages that do not provide libs and build on the target Arch should not be build ever for secondary Arch. Technically ignoring this is also a solution but we can probably do better.

This should be possible to resolve programmatically in haikuporter. 

It's a minor issue though as the extra packages wouldn't really break anything... However dropping secondary Arch packages means a secondary Arch suffix doesn't need to be appended to binaries which I personally would love...

**Comment by pulkomandy** [comment] 2018-10-05 13:32
The secondary arch suffix on binaries is to be used only when both versions of the binary exists (eg for gcc, sdl-config, or the like)

In most cases we will put the x86 binaries in the primary directory.

Things get more complex now because we should get ready for 32/64 hybrids and the needs may be different there. We probably need to rethink the whole primary/secondary arch thing because of this.

**Comment by waddlesplash** [comment] 2018-10-06 19:29
Duplicate of #283.

**Closed by waddlesplash** 2018-10-06 19:29 UTC
