### ISSUE TITLE
GCC11: Fails to use precompiled headers

### ISSUE THREAD

**Issue by nephele-gh** [haikuports/haikuports#9033] opened 2023-07-13 18:21 UTC
I've noticed this when building severall ports.

Here is an example message:
"cc1plus: warning: /sources/nheko-0.11.3/build/CMakeFiles/nheko.dir/cmake_pch.hxx.gch: had text segment at different address [-Winvalid-pch]"

According to a debign bugreport this occurs when gcc is mapped to a different adress, i'd assume it does not use the precompiled header at all in this case.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=696506

**Comment by pulkomandy** [comment] 2023-07-13 18:32
Duplicate of #3875

**Closed by pulkomandy** 2023-07-13 18:32 UTC
