### ISSUE TITLE
clang++ does not support TLS

### ISSUE THREAD

**Issue by Alexco500** [haikuports/haikuports#789] opened 2016-08-31 18:51 UTC
It seems to me that clang++ does not support TLS on haiku. Just check with a small test code:

```
~/Desktop/source/libobjc2-1.7/Buils> cat ./test.cc 

int forward(int receiver, int selector)
{
        __thread static int forwardingSlot;
        forwardingSlot = receiver+selector;
        return forwardingSlot;
}
```

Compile it with gcc (search x86):

```
~/Desktop/source/libobjc2-1.7/Buils> g++ ./test.cc 
./test.cc: In function 'int forward(int, int)':
./test.cc:4:2: warning: '__thread' before 'static'
  __thread static int forwardingSlot;
  ^
/boot/system/develop/lib/x86/start_dyn.o: In function `_start':
start_dyn.c:(.text+0x4c): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

Compiles ok, but does not link, which is correct in this case.

With clang++ I get:

```
~/Desktop/source/libobjc2-1.7/Buils> clang++ ./test.cc 
./test.cc:4:2: error: thread-local storage is not supported for the current
      target
        __thread static int forwardingSlot;
        ^
1 error generated.
```

Since g++ seems to support TLS (and haiku obviously does it, too), clang++ should also support that.

**Comment by return** [comment] 2017-05-19 09:18
I recently ran into this issue when building LLVM with clang, needed by swift. This commit here: https://github.com/llvm-mirror/clang/commit/ef7bceadf4b43c953855013577afac4c2fcb1d62 disables Haiku thread-local storage for clang.

**Comment by pulkomandy** [comment] 2017-05-19 09:37
Maybe try enabling it and see what happens. I think we added TLS support on Haiku side since then?

**Comment by return** [comment] 2017-05-19 15:28
@pulkomandy I tested this on hrev51173 x86_64 with llvm-4.0.0 and it compiled the above test code and it works fine.

**Comment by return** [comment] 2017-06-03 11:44
Has anyone tested llvm-4.0.0-2 on x86 and tried compiling the test code? Until this is confirmed, I think this issue can be closed.

**Comment by return** [comment] 2017-06-05 04:08
The test code compiles and runs fine on x86_gcc4h, when fPIC is passed. Tested on hrev51193 with clang-4.0. Is this enough for this issue to be considered as solved?

**Comment by korli** [comment] 2017-06-08 08:14
Let's close this, support for PIE isn't specific to clang.

**Closed by korli** 2017-06-08 08:14 UTC
Labels: type-bug
