### ISSUE TITLE
Update wpa supplicant to current 2.6 from 2.4

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#2160] opened 2018-01-26 21:51 UTC

**Comment by pulkomandy** [comment] 2018-02-02 16:16
WIP here: https://github.com/pulkomandy/wpa_supplicant-haiku

There were some changes to the internals so our native interface is not reusable as-is. We will need to rework the code a bit. Does not seem to be very hard to do but requires writing some code.

**Comment by pulkomandy** [comment] 2018-02-02 17:11
Duplicate of #1290

**Closed by pulkomandy** 2018-02-02 17:11 UTC
