### ISSUE TITLE
libQt4 failed to build

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#1790] opened 2017-11-12 15:19 UTC
Trying to build libQt4_x86 I get the following error:
`
/boot/system/develop/tools/x86/bin/../lib/gcc/i586-pc-haiku/5.4.0/../../../../i586-pc-haiku/bin/ld: BFD (GNU Binutils) 2.28.1 assertion fail /sources/binutils-2.28.1/bfd/elf32-i386.c:5636
collect2: error: ld returned 1 exit status
Makefile.WebKit.QtWebKit:1196: recipe for target '../../../../../../lib/libQtWebKit.so.4.9.4' failed
make[2]: *** [../../../../../../lib/libQtWebKit.so.4.9.4] Error 1
make[2]: Leaving directory '/sources/qt4-4.8.7-haiku-1/src/3rdparty/webkit/Source/WebKit/qt'
Makefile.WebKit:115: recipe for target 'sub-WebKit-qt-QtWebKit-pro-make_default-ordered' failed
make[1]: *** [sub-WebKit-qt-QtWebKit-pro-make_default-ordered] Error 2
make[1]: Leaving directory '/sources/qt4-4.8.7-haiku-1/src/3rdparty/webkit/Source'
Makefile:747: recipe for target 'sub-webkit-make_default-ordered' failed
make: *** [sub-webkit-make_default-ordered] Error 2
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 2
Error: Build has failed - stopping.
`

**Comment by waddlesplash** [comment] 2017-11-12 15:37
Duplicate of https://github.com/haikuports/haikuports/issues/1750

**Closed by waddlesplash** 2017-11-12 15:37 UTC
