### ISSUE TITLE
Printing support in Qt applications

### ISSUE THREAD

**Issue by bitigchi** [haikuports/haikuports#6483] opened 2021-12-20 18:52 UTC
Opening this issue in lieu of ticket [#17488](https://dev.haiku-os.org/ticket/17488#comment:11). Author mentions that printing is not working in LibreOffice and other applications.

**Comment by korli** [comment] 2021-12-21 08:00
See https://github.com/haikuports/haikuports/issues/3558

**Comment by danboid** [comment] 2021-12-21 19:28
I'm a strong believer that getting LO working well ie with working printing, would be a major boost for the platform. Its an app that most users want to run on a desktop OS. Its majorly crippled without local printing support.

**Comment by diversys** [comment] 2022-05-19 11:02
Closing as a dupe of #3558.

**Closed by diversys** 2022-05-19 11:02 UTC
