### ISSUE TITLE
python 3.6 pip freezes at the end

### ISSUE THREAD

**Issue by victordomingos** [haikuports/haikuports#3420] opened 2018-11-29 12:52 UTC
While installing some package with `pip3`, the Terminal process gets stuck in the end of the install process, even if it's successful. It simply freezes and dosen't get back to the sell prompt. Pressing CTRL+C allows to get control back.

**Comment by pulkomandy** [comment] 2019-06-14 10:51
From HelgeCPH comment in the other isse referred above, we can see that there is a problem with linking a lock file. It writes in /boot/home/config/cache, which is a write enabled directory so this shouldn't be a problem.

The idea in this is that open() is not atomic, and multiple apps could end up managing to create the same file. However, link() is an atomic operation at the filesystem level. So, it is usable to create a file and make sure it is unique. However, BFS does not support hardlinks, so no matter what you try, link() will always fail for us.

Indeed searching for "linklockfile" in pip issue tracker reveals some very similar bugs: https://github.com/pypa/pip/issues?utf8=✓&q=is%3Aissue+is%3Aopen+linklockfile

**Comment by pulkomandy** [comment] 2019-06-14 10:54
So eventually there is not much we can do on our side, except watching https://github.com/pypa/pip/issues/4766 and maybe helping there.

**Comment by probonopd** [comment] 2019-09-15 13:38
Does https://github.com/pypa/pip/pull/6879 resolve this?

**Comment by korli** [comment] 2019-09-16 06:32
> Does [pypa/pip#6879](https://github.com/pypa/pip/pull/6879) resolve this?

let's see when 19.2.4 is released.

**Comment by return** [comment] 2019-11-22 13:07
@korli As of 22 November 2019, pip 19.3.1 was released in October and they have stopped using Lockfile in this version. So it might be worth checking if that version of pip3 has possibly fixed this issue.

**Comment by return** [comment] 2019-11-22 13:45
I can confirm that the pip no longer hangs after package installation in 19.3.1. PR created: See #4399

**Comment by return** [comment] 2019-11-22 22:14
Due to #4399 being merged, this issue can be closed.

**Closed** 2019-11-22 23:18 UTC
Labels: type-bug
