### ISSUE TITLE
StreamRadio Missing symbol: _ZN11BUrlRequest5PauseEv

### ISSUE THREAD

**Issue by smallstepforman** [haikuports/haikuports#6123] opened 2021-08-08 23:26 UTC
With hrev55294, SteamRadio will not start, and comes up with BAlert "Could not open "Stream Radio" (Missing symbol: _ZN11BUrlRequest5PauseEv).

**Comment by smallstepforman** [comment] 2021-08-08 23:39
Sorry, should have added the bug report to https://github.com/HaikuArchives/StreamRadio

**Comment by X547** [comment] 2021-08-08 23:48
https://git.haiku-os.org/haiku/tag/?h=hrev55262

**Comment by korli** [comment] 2021-08-09 04:24
actually the bug report would go to the Haiku bug tracker. the symbols should be kept private for compatibility

**Comment by smallstepforman** [comment] 2021-08-09 04:35
In Haiku's defence, it is a private API, so no guarantees about ABI compatibility.
For another project which used BUrlRequest, I had to bump my program due to API change.  It is a private API so I wasn't too annoyed by the refactoring effort ...

**Comment by korli** [comment] 2021-08-09 11:00
here the problem is the buildbot builds against beta3 Haiku packages, and nightly Haiku package says: "I'm compatible with beta3", accepts to install StreamRadio built for beta3, and refuses to run it.

**Comment by pulkomandy** [comment] 2021-08-09 11:20
Yes, I removed some methods from classes, thinking that it would only affect the version that's in the static library with the private API. But it also affects the deprecated (kept for compatibility) shared library version.

So there are two things to fix:
- In Haiku, restore the pause and resume functions, but only for the deprecated shared version
- In StreamRadio, migrate to the private, statically linked version of the API to avoid the problem and be ready for future Haiku updates

**Comment by pulkomandy** [comment] 2021-08-15 09:47
Haiku side fixed in hrev55310.

**Closed by pulkomandy** 2021-08-15 09:47 UTC
