### ISSUE TITLE
wine-bin 7.9-1 error:24 partial write 64

### ISSUE THREAD

**Issue by bbjimmy** [haikuports/haikuports#10301] opened 2024-04-05 22:24 UTC
x86_64 hrev57689  attempt to launch notepad, WinMine, WineConsole, or Regedit from a Terminal:

~/Desktop> /boot/system/bin/notepad
wine client error:24: partial write 64

etc.

**Comment by waddlesplash** [comment] 2024-04-11 21:06
CC @X547.

**Comment by X547** [comment] 2024-04-11 21:08
Something regression caused by kernel sockets changes?

**Comment by korli** [comment] 2024-04-29 18:54
it would be nice to know one last working hrev before hrev57689.

**Comment by waddlesplash** [comment] 2024-06-26 01:36
Fixed in https://github.com/haiku/haiku/commit/20ac27def64f92a5003e04e2d40d4f9647fc183c.

**Closed by waddlesplash** 2024-06-26 01:36 UTC
Labels: type-bug
