### ISSUE TITLE
UltraDV crashes on launch (no splashscreen)

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#2038] opened 2018-01-02 01:53 UTC
hrev51724 x86_64

Installed UltraDV package from HaikuDepot. App will crash and create four different debugger reports on launch before terminating. No application icon or splashscreen any more.
Two debugger reports pasted below:

Debug information for team /boot/system/apps/UltraDV (1445):
CPU(s): 4x Intel Core™ i5-3570
Memory: 7.95 GiB total, 843.36 MiB used
Haiku revision: hrev51724 Dec 31 2017 15:01:51 (x86_64)

Active Threads:
	thread 1449: w>About BeDV 
	thread 1450: _BMediaRoster_ 
	thread 1455: team 1445 debug task 
	thread 1445: UltraDV (main)
		state: Call (on && off && handler)

Debug information for team /boot/system/apps/Debugger (1482):
CPU(s): 4x Intel Core™ i5-3570
Memory: 7.95 GiB total, 1.01 GiB used
Haiku revision: hrev51724 Dec 31 2017 15:01:51 (x86_64)

Active Threads:
	thread 1482: Debugger (main)
	thread 1483: Local Target Host Loop 
	thread 1484: Local (shredder) 
	thread 1486: DebugReportGenerator 
	thread 1487: team 1445 debug listener 
	thread 1488: team debugger 
	thread 1489: team 1482 debug task 
	thread 1485: worker 
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x7f30f49af2d0	0x11398ae19db	StringUtils::HashValue(char const*) + 0x9 
			Disassembly:
				StringUtils::HashValue(char const*):
				0x0000011398ae19d2:               55  push %rbp
				0x0000011398ae19d3:           4889e5  mov %rsp, %rbp
				0x0000011398ae19d6:           4885ff  test %rdi, %rdi
				0x0000011398ae19d9:             7432  jz 0x98ae1a0d
				0x0000011398ae19db:           0fb617  movzx (%rdi), %edx <--

			Frame memory:
				[0x7f30f49af2c0]  ....0...........   a0 f5 9a f4 30 7f 00 00 c4 ca ab 98 13 01 00 00
		0x7f30f49af5b0	0x11398abcabf	FileManager::Domain::GetFile(BString const&) + 0xaf1 
		0x7f30f49af600	0x11398ab72a2	FileManager::GetSourceFile(BString const&, BString const&) + 0x86 
		0x7f30f49af700	0x11398a95326	DwarfImageDebugInfo::GetFunctions(BObjectList<SymbolInfo> const&, BObjectList<FunctionDebugInfo>&) + 0x1de 
		0x7f30f49af7c0	0x11398aa570f	ImageDebugInfo::FinishInit(DebuggerInterface*) + 0xed 
		0x7f30f49af840	0x11398aa6eb4	TeamDebugInfo::LoadImageDebugInfo(ImageInfo const&, LocatableFile*, ImageDebugInfoLoadingState&, ImageDebugInfo*&) + 0xf0 
		0x7f30f49af8e0	0x11398abfe75	LoadImageDebugInfoJob::Do() + 0x89 
		0x7f30f49af910	0x11398ae3240	Worker::_ProcessJobs() + 0x144 
		0x7f30f49af940	0x11398ae3348	Worker::_WorkerLoop() + 0x10 
		0x7f30f49af950	0x11398ae33f6	Worker::_WorkerLoopEntry(void*) + 0x4 
		0x7f30f49af970	0x50398efb4f	thread_entry + 0x10 
		00000000	0x7fd971e9f260	commpage_thread_exit + 0 

		Registers:
			  rip:	0x0000011398ae19db
			  rsp:	0x00007f30f49af2c0
			  rbp:	0x00007f30f49af2c0
			  rax:	0x0000000000000000
			  rbx:	0x000000a13e58b790
			  rcx:	0x0000000000000010
			  rdx:	0x000000a13f2ee0a0
			  rsi:	0x000000000000002f
			  rdi:	0x000000000000000f
			   r8:	0x000000000000002f
			   r9:	0x0000000000000080
			  r10:	0x000000000000007f
			  r11:	0x0000000000000001
			  r12:	0x0000000000000000
			  r13:	0x4965747562697203
			  r14:	0x000000a140c5bfb0
			  r15:	0x000000a134c7b200
			   cs:	0x0023
			   ds:	0x0000
			   es:	0x0000
			   fs:	0x0000
			   gs:	0x0000
			   ss:	0x001b
			  st0:	0
			  st1:	0
			  st2:	0
			  st3:	0
			  st4:	0
			  st5:	0
			  st6:	0
			  st7:	0
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0, 0}
			  mm7:	{0, 0, 0, 0}
			 xmm0:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm1:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm8:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm9:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm10:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm11:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm12:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm13:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm14:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm15:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	3082	0x50398b1000	0x5039a09000	0x5039c08000	0x5039c5b000	lib    	/boot/system/lib/libroot.so
	3072	0x50bd2d6000	0x50bd2f7000	0x50bd4f6000	0x50bd4f8000	lib    	/boot/system/runtime_loader
	3084	0x7704214000	0x7705a92000	0x7705c91000	0x7705c92000	lib    	/boot/system/lib/libicudata.so.57.1
	3078	0x7faaa6c000	0x7faaa71000	0x7faac70000	0x7faac71000	lib    	/boot/system/lib/libbsd.so
	3103	0x99d38ea000	0x99d3967000	0x99d3b66000	0x99d3b68000	lib    	/boot/system/lib/libsolv.so.0
	3100	0x9de8f92000	0x9de908e000	0x9de928e000	0x9de9291000	lib    	/boot/system/lib/libtextencoding.so
	3086	0xb898c18000	0xb898c24000	0xb898e23000	0xb898e25000	lib    	/boot/system/lib/libicuio.so.57.1
	3089	0xc49c12f000	0xc49c15e000	0xc49c35e000	0xc49c392000	lib    	/boot/system/lib/libicutu.so.57.1
	3073	0xc579163000	0xc57924b000	0xc57944b000	0xc57945c000	app    	/boot/system/apps/Debugger
	3099	0xe8d2686000	0xe8d26f1000	0xe8d28f0000	0xe8d28fb000	lib    	/boot/system/lib/libssl.so.1.0.0
	3079	0x11398988000	0x11398b49000	0x11398d48000	0x11398d83000	lib    	/boot/system/lib/libdebugger.so
	3093	0x11c1fba5000	0x11c1fc09000	0x11c1fe08000	0x11c1fe0d000	lib    	/boot/system/lib/libbnetapi.so
	3080	0x1282cf0a000	0x1282cf60000	0x1282d15f000	0x1282d164000	lib    	/boot/system/lib/libncurses.so.6.0.0
	3096	0x145b6854000	0x145b6869000	0x145b6a68000	0x145b6a6a000	lib    	/boot/system/lib/libtranslation.so
	3076	0x14a02dc5000	0x14a02e5d000	0x14a0305c000	0x14a03062000	lib    	/boot/system/lib/libpackage.so
	3092	0x16165ec1000	0x16165f5a000	0x16166159000	0x1616615a000	lib    	/boot/system/lib/libzstd.so.1.3.2
	3090	0x16b419de000	0x16b41b76000	0x16b41d75000	0x16b41d8a000	lib    	/boot/system/lib/libicuuc.so.57.1
	3081	0x16ec0a9f000	0x16ec0ad3000	0x16ec0cd3000	0x16ec0cd9000	lib    	/boot/system/lib/libedit.so.0.0.53
	3075	0x1854fec9000	0x185501cc000	0x185503cb000	0x185503f9000	lib    	/boot/system/lib/libbe.so
	3091	0x197a86f3000	0x197a870f000	0x197a890e000	0x197a890f000	lib    	/boot/system/lib/libz.so.1.2.11
	3097	0x1a34ccd7000	0x1a34cce5000	0x1a34cee5000	0x1a34cee6000	lib    	/boot/system/lib/libdebug.so
	3104	0x1ae70695000	0x1ae706a4000	0x1ae708a4000	0x1ae708a5000	lib    	/boot/system/lib/libsolvext.so.0
	3102	0x1c52b12e000	0x1c52b137000	0x1c52b337000	0x1c52b338000	lib    	/boot/system/lib/libpackage-add-on-libsolv.so
	3094	0x1c9f8838000	0x1c9f88a3000	0x1c9f8aa2000	0x1c9f8aa5000	lib    	/boot/system/lib/libcurl.so.4.5.0
	3085	0x1d409c6c000	0x1d409ee9000	0x1d40a0e8000	0x1d40a0fd000	lib    	/boot/system/lib/libicui18n.so.57.1
	3077	0x1d9aebca000	0x1d9aed62000	0x1d9aef62000	0x1d9aef7b000	lib    	/boot/system/lib/libtracker.so
	3095	0x1e897f09000	0x1e897f48000	0x1e898147000	0x1e898150000	lib    	/boot/system/lib/libnetwork.so
	3083	0x1ece6419000	0x1ece642e000	0x1ece662d000	0x1ece662e000	lib    	/boot/system/lib/libgcc_s.so.1
	3088	0x1f3bcd3d000	0x1f3bcd48000	0x1f3bcf48000	0x1f3bcf49000	lib    	/boot/system/lib/libiculx.so.57.1
	3087	0x1fa34729000	0x1fa3477e000	0x1fa3497e000	0x1fa34981000	lib    	/boot/system/lib/libicule.so.57.1
	3074	0x1fc0211f000	0x1fc02281000	0x1fc02481000	0x1fc02495000	lib    	/boot/system/lib/libstdc++.so.6.0.21
	3098	0x264e887e000	0x264e8a8a000	0x264e8c8a000	0x264e8cb3000	lib    	/boot/system/lib/libcrypto.so.1.0.0
	3071	0x7fd971e9f000	0x7fd971ea7000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	10298	0x1501da000	0x1501f2000	        96	rw-        	full          	rld heap
	10297	0x28a048000	0x28a060000	        96	rw-        	full          	rld heap
	10296	0x31ee07000	0x31ee17000	        64	rw-        	full          	rld heap
	10295	0x4e2e28000	0x4e2e38000	        64	rw-        	full          	rld heap
	10294	0x11817e2000	0x11817ea000	        32	rw-        	full          	rld heap
	10293	0x16b01aa000	0x16b01b2000	        32	rw-        	full          	rld heap
	10228	0x1ff6ee2000	0x1ff6ee3000	         4	rw-S       	full          	_rld_debug_
	10227	0x22b864c000	0x22b865c000	        64	rw-        	full          	rld heap
	10251	0x50398b1000	0x5039a09000	      1376	r-x        	full          	libroot.so_seg0ro
	10252	0x5039c08000	0x5039c16000	        56	rw-        	full          	libroot.so_seg1rw
	10253	0x5039c16000	0x5039c5b000	       276	rw-        	full          	libroot.so_seg2rw
	10225	0x50bd2d6000	0x50bd2f7000	       132	r-x        	full          	runtime_loader_seg0ro
	10226	0x50bd4f6000	0x50bd4f8000	         8	rw-        	full          	runtime_loader_seg1rw
	10256	0x7704214000	0x7705a92000	     25080	r-x        	full          	libicudata.so.57.1_seg0ro
	10257	0x7705c91000	0x7705c92000	         4	rw-        	full          	libicudata.so.57.1_seg1rw
	10241	0x7faaa6c000	0x7faaa71000	        20	r-x        	full          	libbsd.so_seg0ro
	10242	0x7faac70000	0x7faac71000	         4	rw-        	full          	libbsd.so_seg1rw
	10316	0x99d38ea000	0x99d3967000	       500	r-x        	full          	libsolv.so.0_seg0ro
	10318	0x99d3b66000	0x99d3b68000	         8	rw-        	full          	libsolv.so.0_seg1rw
	10291	0x9de8f92000	0x9de908e000	      1008	r-x        	full          	libtextencoding.so_seg0ro
	10292	0x9de928e000	0x9de9291000	        12	rw-        	full          	libtextencoding.so_seg1rw
	10299	0xa134c5e000	0xa140c6e000	    196672	rw-        	full          	heap
	10260	0xb898c18000	0xb898c24000	        48	r-x        	full          	libicuio.so.57.1_seg0ro
	10261	0xb898e23000	0xb898e25000	         8	rw-        	full          	libicuio.so.57.1_seg1rw
	10266	0xc49c12f000	0xc49c15e000	       188	r-x        	full          	libicutu.so.57.1_seg0ro
	10267	0xc49c35e000	0xc49c360000	         8	rw-        	full          	libicutu.so.57.1_seg1rw
	10268	0xc49c360000	0xc49c392000	       200	rw-        	full          	libicutu.so.57.1_seg2rw
	10229	0xc579163000	0xc57924b000	       928	r-x        	full          	Debugger_seg0ro
	10230	0xc57944b000	0xc57945c000	        68	rw-        	full          	Debugger_seg1rw
	10289	0xe8d2686000	0xe8d26f1000	       428	r-x        	full          	libssl.so.1.0.0_seg0ro
	10290	0xe8d28f0000	0xe8d28fb000	        44	rw-        	full          	libssl.so.1.0.0_seg1rw
	10243	0x11398988000	0x11398b49000	      1796	r-x        	full          	libdebugger.so_seg0ro
	10244	0x11398d48000	0x11398d82000	       232	rw-        	full          	libdebugger.so_seg1rw
	10245	0x11398d82000	0x11398d83000	         4	rw-        	full          	libdebugger.so_seg2rw
	10275	0x11c1fba5000	0x11c1fc09000	       400	r-x        	full          	libbnetapi.so_seg0ro
	10276	0x11c1fe08000	0x11c1fe0d000	        20	rw-        	full          	libbnetapi.so_seg1rw
	10246	0x1282cf0a000	0x1282cf60000	       344	r-x        	full          	libncurses.so.6.0.0_seg0ro
	10247	0x1282d15f000	0x1282d164000	        20	rw-        	full          	libncurses.so.6.0.0_seg1rw
	10282	0x145b6854000	0x145b6869000	        84	r-x        	full          	libtranslation.so_seg0ro
	10283	0x145b6a68000	0x145b6a6a000	         8	rw-        	full          	libtranslation.so_seg1rw
	10236	0x14a02dc5000	0x14a02e5d000	       608	r-x        	full          	libpackage.so_seg0ro
	10237	0x14a0305c000	0x14a03062000	        24	rw-        	full          	libpackage.so_seg1rw
	10273	0x16165ec1000	0x16165f5a000	       612	r-x        	full          	libzstd.so.1.3.2_seg0ro
	10274	0x16166159000	0x1616615a000	         4	rw-        	full          	libzstd.so.1.3.2_seg1rw
	10269	0x16b419de000	0x16b41b76000	      1632	r-x        	full          	libicuuc.so.57.1_seg0ro
	10270	0x16b41d75000	0x16b41d8a000	        84	rw-        	full          	libicuuc.so.57.1_seg1rw
	10248	0x16ec0a9f000	0x16ec0ad3000	       208	r-x        	full          	libedit.so.0.0.53_seg0ro
	10249	0x16ec0cd3000	0x16ec0cd6000	        12	rw-        	full          	libedit.so.0.0.53_seg1rw
	10250	0x16ec0cd6000	0x16ec0cd9000	        12	rw-        	full          	libedit.so.0.0.53_seg2rw
	10234	0x1854fec9000	0x185501cc000	      3084	r-x        	full          	libbe.so_seg0ro
	10235	0x185503cb000	0x185503f9000	       184	rw-        	full          	libbe.so_seg1rw
	10271	0x197a86f3000	0x197a870f000	       112	r-x        	full          	libz.so.1.2.11_seg0ro
	10272	0x197a890e000	0x197a890f000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	10284	0x1a34ccd7000	0x1a34cce5000	        56	r-x        	full          	libdebug.so_seg0ro
	10285	0x1a34cee5000	0x1a34cee6000	         4	rw-        	full          	libdebug.so_seg1rw
	10319	0x1ae70695000	0x1ae706a4000	        60	r-x        	full          	libsolvext.so.0_seg0ro
	10320	0x1ae708a4000	0x1ae708a5000	         4	rw-        	full          	libsolvext.so.0_seg1rw
	10314	0x1c52b12e000	0x1c52b137000	        36	r-x        	full          	libpackage-add-on-libsolv.so_se
	10315	0x1c52b337000	0x1c52b338000	         4	rw-        	full          	libpackage-add-on-libsolv.so_se
	10277	0x1c9f8838000	0x1c9f88a3000	       428	r-x        	full          	libcurl.so.4.5.0_seg0ro
	10278	0x1c9f8aa2000	0x1c9f8aa5000	        12	rw-        	full          	libcurl.so.4.5.0_seg1rw
	10258	0x1d409c6c000	0x1d409ee9000	      2548	r-x        	full          	libicui18n.so.57.1_seg0ro
	10259	0x1d40a0e8000	0x1d40a0fd000	        84	rw-        	full          	libicui18n.so.57.1_seg1rw
	10238	0x1d9aebca000	0x1d9aed62000	      1632	r-x        	full          	libtracker.so_seg0ro
	10239	0x1d9aef62000	0x1d9aef7a000	        96	rw-        	full          	libtracker.so_seg1rw
	10240	0x1d9aef7a000	0x1d9aef7b000	         4	rw-        	full          	libtracker.so_seg2rw
	10279	0x1e897f09000	0x1e897f48000	       252	r-x        	full          	libnetwork.so_seg0ro
	10280	0x1e898147000	0x1e89814a000	        12	rw-        	full          	libnetwork.so_seg1rw
	10281	0x1e89814a000	0x1e898150000	        24	rw-        	full          	libnetwork.so_seg2rw
	10254	0x1ece6419000	0x1ece642e000	        84	r-x        	full          	libgcc_s.so.1_seg0ro
	10255	0x1ece662d000	0x1ece662e000	         4	rw-        	full          	libgcc_s.so.1_seg1rw
	10264	0x1f3bcd3d000	0x1f3bcd48000	        44	r-x        	full          	libiculx.so.57.1_seg0ro
	10265	0x1f3bcf48000	0x1f3bcf49000	         4	rw-        	full          	libiculx.so.57.1_seg1rw
	10262	0x1fa34729000	0x1fa3477e000	       340	r-x        	full          	libicule.so.57.1_seg0ro
	10263	0x1fa3497e000	0x1fa34981000	        12	rw-        	full          	libicule.so.57.1_seg1rw
	10231	0x1fc0211f000	0x1fc02281000	      1416	r-x        	full          	libstdc++.so.6.0.21_seg0ro
	10232	0x1fc02481000	0x1fc0248d000	        48	rw-        	full          	libstdc++.so.6.0.21_seg1rw
	10233	0x1fc0248d000	0x1fc02495000	        32	rw-        	full          	libstdc++.so.6.0.21_seg2rw
	10286	0x264e887e000	0x264e8a8a000	      2096	r-x        	full          	libcrypto.so.1.0.0_seg0ro
	10287	0x264e8c8a000	0x264e8cb1000	       156	rw-        	full          	libcrypto.so.1.0.0_seg1rw
	10288	0x264e8cb1000	0x264e8cb3000	         8	rw-        	full          	libcrypto.so.1.0.0_seg2rw
	10307	0x7f30f496c000	0x7f30f49b1000	       276	rw-s       	full          	worker_1485_stack
	10311	0x7f5384b8f000	0x7f5384bd4000	       276	rw-s       	full          	team 1445 debug listener_1487_s
	10309	0x7f812e209000	0x7f812e24e000	       276	rw-s       	full          	DebugReportGenerator_1486_stack
	10305	0x7f83bf282000	0x7f83bf2c7000	       276	rw-s       	full          	Local (shredder)_1484_stack
	10303	0x7f933b09e000	0x7f933b0e3000	       276	rw-s       	full          	Local Target Host Loop_1483_sta
	10313	0x7fc9f16f8000	0x7fc9f173d000	       276	rw-s       	full          	team debugger_1488_stack
	10224	0x7fd971e9f000	0x7fd971ea7000	        32	r-xSk      	full          	commpage
	10223	0x7fdca0073000	0x7fdca1074000	     16388	rw-s       	full          	Debugger_1482_stack
	10221	0x7fdcda58b000	0x7fdcda58f000	        16	rw-        	full          	user area

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	50928	    0	          0	some BBlockCache lock
	50929	    0	          0	Catalog
	50930	    0	          0	some BLocker
	50931	    0	          0	some BLocker
	50932	    0	          0	token space
	50933	    0	       1488	BLooperList lock
	50934	    0	          0	AppServerLink_sLock
	50935	    0	          0	LocaleRosterData
	50936	    0	          0	some BLocker
	50937	    0	          0	synchronized hash map
	50938	    0	          0	synchronized hash map
	50939	    0	          0	some BLocker
	50940	    0	          0	DNS cache
	50942	    0	          0	Catalog
	50943	    0	          0	PeriodicUpdatePoses
	50944	    0	          0	Light Lock
	50945	    0	          0	Light Lock
	50946	    0	          0	undo
	50947	    0	          0	some BLocker
	50948	    0	          0	some BLocker
	50949	    0	          0	type handler roster
	50950	    0	          0	type handler roster
	50951	    0	          0	some BLocker
	50952	    0	          0	BMessageQueue Lock
	50953	    0	       1484	anonymous looper
	50954	    0	          0	some BLocker
	50961	    0	          0	debug context pool
	50962	    0	          0	debug context pool block
	50963	    0	          0	BMessageQueue Lock
	50964	    0	          0	team debugger
	50965	    0	          0	file manager
	50966	    0	          0	team debug info
	50967	    0	          0	global type cache
	50968	    0	          0	dwarf manager
	50969	    0	       1488	team lock
	50970	    0	          0	worker
	50971	    2	       1485	work to do
	50975	    0	          0	breakpoint manager
	50976	    0	          0	watchpoint manager
	50977	    0	          0	some BLocker
	50978	    0	          0	BMessageQueue Lock
	50979	    0	          0	DebugReportGenerator
	50980	   -1	          0	debug_controller_data_wait
	50981	    0	          0	value node container
	50985	    0	          0	breakpoint condition waiter
	50986	    0	          0	breakpoint condition waiter
	50987	    0	          0	breakpoint condition waiter
	50988	    0	          0	breakpoint condition waiter
	50995	    0	       1482	show report
	50996	   -1	          0	report generator wait
	50997	    0	          0	dwarf image debug info
	50998	    0	          0	dwarf image debug info
	50999	    0	          0	dwarf image debug info
	51000	    0	          0	dwarf image debug info
	51001	    0	          0	dwarf image debug info
	51002	    0	          0	dwarf image debug info
	51003	    0	          0	dwarf image debug info
	51004	    0	          0	dwarf image debug info
	51005	    0	          0	dwarf image debug info
	51006	    0	          0	dwarf image debug info
	51007	    0	          0	dwarf image debug info
	51008	    0	          0	dwarf image debug info
	51009	    0	          0	dwarf image debug info
	51010	    0	          0	dwarf image debug info
	51011	    0	          0	dwarf image debug info
	51012	    0	          0	dwarf image debug info
	51013	    0	          0	dwarf image debug info
	51014	    0	          0	dwarf image debug info
	51015	    0	          0	dwarf image debug info
	51016	    0	          0	dwarf image debug info
	51017	    0	          0	dwarf image debug info
	51018	    0	          0	dwarf image debug info
	51019	    0	          0	dwarf image debug info
	51020	    0	          0	dwarf image debug info
	51021	    0	          0	dwarf image debug info
	51022	    0	          0	dwarf image debug info
	51023	    0	          0	dwarf image debug info
	51024	    0	          0	dwarf image debug info
	51025	    0	          0	dwarf image debug info
	51026	    0	          0	dwarf image debug info
	51027	    0	          0	dwarf image debug info
	51028	    0	          0	dwarf image debug info
	51029	    0	          0	dwarf image debug info
	51030	    0	          0	dwarf image debug info
	51031	    0	          0	dwarf image debug info
	51032	    0	          0	dwarf image debug info
	51033	    0	          0	dwarf image debug info
	51034	    0	          0	dwarf image debug info
	51035	    0	          0	dwarf image debug info
	51036	    0	          0	dwarf image debug info
	51037	    0	          0	dwarf image debug info
	51038	    0	          0	dwarf image debug info
	51039	    0	          0	dwarf image debug info
	51040	    0	          0	dwarf image debug info
	51041	    0	          0	dwarf image debug info
	51042	    0	          0	dwarf image debug info
	51043	    0	          0	dwarf image debug info
	51044	    0	          0	dwarf image debug info
	51045	    0	          0	dwarf image debug info
	51046	    0	          0	dwarf image debug info
	51047	    0	          0	dwarf image debug info
	51048	    0	          0	dwarf image debug info
	51049	    0	          0	dwarf image debug info
	51050	    0	          0	dwarf image debug info
	51051	    0	          0	dwarf image debug info
	51052	    0	          0	dwarf image debug info
	51053	    0	          0	dwarf image debug info
	51054	    0	          0	dwarf image debug info
	51055	    0	          0	dwarf image debug info

**Comment by fbrosson** [comment] 2018-01-02 07:37
**Short story:** UltraDV crashes if we strip the runtime, so we cannot have a debuginfo package for it.

**Long story:** I understood what happened when I tried to fix #2037:
* I first updated to the latest git revision, fixed `INSTALL()` to add the call to `addAppDeskbarSymlink`, created and tested the package on x86_gcc2, found that it was working fine.
* Then I switched to x86_64, and there, I though about adding the debuginfo package. Built the app, installed the main package and it's debuginfo. Tested and found that it was crashing. Thought that the crash (on x86_64) was caused by the update, but it was actually being caused by the strip, which is required for the debuginfo package.

**Conclusion:** stripping can cause an unstripped working runtime to stop working.

Closing this since it is now fixed, hopefully :)

**Closed by fbrosson** 2018-01-02 07:37 UTC
