### ISSUE TITLE
perl's XML::Parser fails in current x86_64 nightly build

### ISSUE THREAD

**Issue by schumaml** [haikuports/haikuports#1640] opened 2017-09-16 07:05 UTC
Hi,

I'm currently trying to build some software which requires intltool. With this not being available, I tried to build intltool itself, and ran into 

`checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool`

The xml_parser package is installed, but config.log revealed that it crashes. 
This can be provoked more directly via the following command in a terminal:

`~> perl -e "require XML::Parser"`

and this yields:

> Can't load '/packages/perl-5.18.2-3/.self/lib/perl5/vendor_perl/5.18.2/x86_64-haiku/auto/XML/Parser/Expat/Expat.so' for module XML::Parser::Expat: Missing library at /packages/perl-5.18.2-3/.self/lib/perl5/5.18.2/x86_64-haiku/DynaLoader.pm line 190.
>  at /packages/perl-5.18.2-3/.self/lib/perl5/vendor_perl/5.18.2/x86_64-haiku/XML/Parser.pm line 18.
> Compilation failed in require at /packages/perl-5.18.2-3/.self/lib/perl5/vendor_perl/5.18.2/x86_64-haiku/XML/Parser.pm line 18.
> BEGIN failed--compilation aborted at /packages/perl-5.18.2-3/.self/lib/perl5/vendor_perl/5.18.2/x86_64-haiku/XML/Parser.pm line 22.
> Compilation failed in require at -e line 1.

**Comment by diversys** [comment] 2017-09-16 07:19
Looks like a dupe of #1518

**Comment by schumaml** [comment] 2017-09-16 07:43
Seen that, but it is not an obvious match - all points towards an 5.18.2 XML::Parser failing with a 5.18.2 perl.

#1518 is specifically about intltool - and having a working version of that is nice, of course - but the issue itself will still affect people who just want to use perl.

**Comment by diversys** [comment] 2017-09-16 08:35
`-fstack-protector` was disabled in xml_parser in 5395472421c5aa847bf6e30bfb380c994bd59748
however building it with perl 5.18.2-3 still makes Expat.so link against libssp.so.0.
Reverting the commit above fixes it.

**Comment by korli** [comment] 2017-09-16 09:07
Perl 5.26 is the master branch version. 5.18 is on the 2017Q3.

**Comment by schumaml** [comment] 2017-09-16 09:14
5.18.2 is what you get with the current nightly. Installed it just yesterday - and I ran the updater to check if any updates are available. 

I am aware that a possible resolution might be a software update, likely from this experimental  eu.hpkg.haiku-os.org/ repository. 

I know that I could fix this for myself right now, but in my book the point of bug reports is to fix things for everyone :)

**Comment by korli** [comment] 2017-09-16 09:17
Sure. I'm just stating it is fixed in master. Prebuilt packages will be made available when master is ready/branched.

**Comment by korli** [comment] 2017-10-07 18:04
Should be fixed with perl 5.26

**Closed by korli** 2017-10-07 18:04 UTC
