### ISSUE TITLE
kompare: "Could not load KompareViewPart"

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#6916] opened 2022-05-13 16:02 UTC
This is on Haiku hrev56098, 64bit.
When trying to launch, I get an alert: "Could not load KompareViewPart"

If the recipe get bumped, you may also want to check the DESCRIPTION. There are hard newlines that sould be removed.

**Comment by threedeyes** [comment] 2022-05-14 01:24
All KDE-framework packages was updated?
I can't reproduce this bug on x64 nightly build

**Comment by threedeyes** [comment] 2022-05-14 01:54
DESCRIPTION fixed in https://github.com/haikuports/haikuports/commit/e1e4c49b8850de85a983198cc74b55633ef8bbae

![2022-05-14_11-55](https://user-images.githubusercontent.com/2559260/168406567-a1b1cd17-79b0-42b3-a7d4-a250548552cc.png)

**Comment by humdingerb** [comment] 2022-05-14 06:29
Weird. Still got the same error. I'm totally up-to-date:

```
~/Desktop> pkgman full
100% repochecksum-1 [65 bytes]
Validating checksum for Haiku...done.
100% repochecksum-1 [64 bytes]
Validating checksum for HaikuPorts...done.
Nothing to do.
```

Maybe off-topic: what's the "repocache-2" of HaikuPorts in your shot?

**Comment by threedeyes** [comment] 2022-05-14 10:05
It seems to me that there is no implicit dependence. Try running it from the terminal - maybe there will be an error in the log.

>Maybe off-topic: what's the "repocache-2" of HaikuPorts in your shot?
I don't know. I only have two repositories enabled at the moment.

**Comment by threedeyes** [comment] 2022-05-14 11:33
Install **shared_mime_info** package and run from terminal **kbuildcycoca5** utility and try again

**Comment by humdingerb** [comment] 2022-05-15 05:37
Thanks! Indeed, installing the shared_mime_info package did the trick.

**Comment by threedeyes** [comment] 2022-05-16 13:28
Fixed in https://github.com/haikuports/haikuports/commit/bd13b43d9c5fea63876c4ac7239b1218fb2b35e4

**Closed by threedeyes** 2022-05-16 13:28 UTC
