### ISSUE TITLE
wxqt needs a bump

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#2837] opened 2018-07-21 22:00 UTC
gcc changed, wx needs a rebuild

**Comment by waddlesplash** [comment] 2018-07-25 21:54
Dupe of #1779?

**Comment by extrowerk** [comment] 2018-07-26 05:42
No. Building and running something with wx the program will complain about the mix-match compiler. A wx rebuild solved it.

**Closed** 2018-11-03 20:45 UTC
Labels: task
