### ISSUE TITLE
LibreOffice 6.4.7.2-10 stoped working (32 bit)

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#9219] opened 2023-08-15 01:09 UTC
Hello. After recent update, LibreOffice stopped working. When trying to start the application from Terminal, I get the following error:

```
/boot/system/apps/LibreOffice> ./'LibreOffice Calc' 
runtime_loader: /boot/system/add-ons/x86/locale/catalogs/IFF: Could not resolve symbol '_Z15convert_to_utf8mPKcPlPcS1_S1_c'
resolve symbol "_Z15convert_to_utf8mPKcPlPcS1_S1_c" returned: -2147478780
runtime_loader: /boot/system/add-ons/x86/locale/catalogs/IFF: Troubles relocating: Symbol not found
/boot/system/apps/LibreOffice> warn:sal.osl:1026:1:sal/osl/unx/thread.cxx:1026: RTL_TEXTENCODING_DONTKNOW -> _ASCII_US
warn:configmgr:1026:1:configmgr/source/xcuparser.cxx:289: unknown component "org.openoffice.Office.UI.DbReportWindowState" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/registry_en-US.xcd"
warn:configmgr:1026:1:configmgr/source/xcuparser.cxx:289: unknown component "org.openoffice.Office.UI.ReportCommands" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/registry_en-US.xcd"
warn:configmgr:1026:1:configmgr/source/xcuparser.cxx:901: ignoring modify of unknown set member node "StarOffice XML (Base) Report" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/fcfg_langpack_en-US.xcd"
warn:configmgr:1026:1:configmgr/source/xcuparser.cxx:901: ignoring modify of unknown set member node "StarOffice XML (Base) Report Chart" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/fcfg_langpack_en-US.xcd"
warn:i18nlangtag:1026:1:i18nlangtag/source/languagetag/languagetag.cxx:1568: LanguageTag::getLanguageFromLangtag: pLangT==NULL for 'UTF-8'
warn:i18nlangtag:1026:1:i18nlangtag/source/languagetag/languagetag.cxx:1626: LanguageTag::getRegionFromLangtag: pRegionT==NULL for 'UTF-8'
warn:i18nlangtag:1026:1:i18nlangtag/source/languagetag/languagetag.cxx:1396: LanguageTagImpl::convertLocaleToLang: with bAllowOnTheFlyID invalid 'UTF-8'
warn:i18nlangtag:1026:1:i18nlangtag/source/languagetag/languagetag.cxx:694: LanguageTag::setConfiguredSystemLanguage: refusing to set unresolved system locale 0x3ff
warn:i18nlangtag:1026:1:i18nlangtag/source/languagetag/languagetag.cxx:1520: LanguageTag(rtl_Locale) - unknown: UT_F-8
warn:i18nlangtag:1026:1:i18nlangtag/source/languagetag/languagetag.cxx:1520: LanguageTag(rtl_Locale) - unknown: UT_F-8
warn:i18nlangtag:1026:1:i18nlangtag/source/languagetag/languagetag.cxx:1520: LanguageTag(rtl_Locale) - unknown: UT_F-8
warn:i18nlangtag:1026:1:i18nlangtag/source/languagetag/languagetag.cxx:1520: LanguageTag(rtl_Locale) - unknown: UT_F-8
Fontconfig warning: ignoring UTF-8: not a valid region tag
terminate called after throwing an instance of 'com::sun::star::ucb::InteractiveAugmentedIOException'
Abort
Application Error

/boot/system/apps/LibreOffice> 

```

**Comment by waddlesplash** [comment] 2023-08-15 01:15
This looks strange. Can anyone else reproduce the problem?

**Comment by unspacyar** [comment] 2023-08-15 01:37
In case could help, on hrev57184 from August 2, LibreOffice starts successfully.  There is the output from Terminal. Lot of warnings, but the applications starts fine:

```
/boot/system/apps/LibreOffice> ./'LibreOffice Calc' 
runtime_loader: /boot/system/add-ons/x86/locale/catalogs/IFF: Could not resolve symbol '_Z15convert_to_utf8mPKcPlPcS1_S1_c'
resolve symbol "_Z15convert_to_utf8mPKcPlPcS1_S1_c" returned: -2147478780
runtime_loader: /boot/system/add-ons/x86/locale/catalogs/IFF: Troubles relocating: Symbol not found
/boot/system/apps/LibreOffice> warn:sal.osl:905:1:sal/osl/unx/thread.cxx:1026: RTL_TEXTENCODING_DONTKNOW -> _ASCII_US
warn:configmgr:905:1:configmgr/source/xcuparser.cxx:289: unknown component "org.openoffice.Office.UI.DbReportWindowState" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/registry_en-US.xcd"
warn:configmgr:905:1:configmgr/source/xcuparser.cxx:289: unknown component "org.openoffice.Office.UI.ReportCommands" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/registry_en-US.xcd"
warn:configmgr:905:1:configmgr/source/xcuparser.cxx:901: ignoring modify of unknown set member node "StarOffice XML (Base) Report" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/fcfg_langpack_en-US.xcd"
warn:configmgr:905:1:configmgr/source/xcuparser.cxx:901: ignoring modify of unknown set member node "StarOffice XML (Base) Report Chart" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/fcfg_langpack_en-US.xcd"
warn:i18nlangtag:905:1:i18nlangtag/source/languagetag/languagetag.cxx:1568: LanguageTag::getLanguageFromLangtag: pLangT==NULL for 'UTF-8'
warn:i18nlangtag:905:1:i18nlangtag/source/languagetag/languagetag.cxx:1626: LanguageTag::getRegionFromLangtag: pRegionT==NULL for 'UTF-8'
warn:i18nlangtag:905:1:i18nlangtag/source/languagetag/languagetag.cxx:1396: LanguageTagImpl::convertLocaleToLang: with bAllowOnTheFlyID invalid 'UTF-8'
warn:i18nlangtag:905:1:i18nlangtag/source/languagetag/languagetag.cxx:694: LanguageTag::setConfiguredSystemLanguage: refusing to set unresolved system locale 0x3ff
warn:i18nlangtag:905:1:i18nlangtag/source/languagetag/languagetag.cxx:1520: LanguageTag(rtl_Locale) - unknown: UT_F-8
warn:i18nlangtag:905:1:i18nlangtag/source/languagetag/languagetag.cxx:1520: LanguageTag(rtl_Locale) - unknown: UT_F-8
warn:i18nlangtag:905:1:i18nlangtag/source/languagetag/languagetag.cxx:1520: LanguageTag(rtl_Locale) - unknown: UT_F-8
warn:i18nlangtag:905:1:i18nlangtag/source/languagetag/languagetag.cxx:1520: LanguageTag(rtl_Locale) - unknown: UT_F-8
Fontconfig warning: ignoring UTF-8: not a valid region tag
warn:sfx.view:905:1:sfx2/source/view/viewfrm.cxx:3226: SID_SIDEBAR state requested, but no task pane child window exists for this ID!
warn:sfx.control:905:1:sfx2/source/control/dispatch.cxx:1310: Childwindow slot missing: 25917
warn:sfx.control:905:1:sfx2/source/control/dispatch.cxx:1310: Childwindow slot missing: 25917
/boot/system/apps/LibreOffice> 
```

**Comment by Begasus** [comment] 2023-08-21 10:14
Same problem here, found somthing here:
https://bugzilla.redhat.com/show_bug.cgi?id=1610964

Maybe related to binutils update? (just guessing)
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/5STOG6CETD5UVN5INQPL5XXC3MYKMW3W/

**Comment by pulkomandy** [comment] 2023-08-21 10:56
These bugreports are for patches done in Redhat/Fedora that wouldn't affect us.

{{{
runtime_loader: /boot/system/add-ons/x86/locale/catalogs/IFF: Could not resolve symbol '_Z15convert_to_utf8mPKcPlPcS1_S1_c'
resolve symbol "_Z15convert_to_utf8mPKcPlPcS1_S1_c" returned: -2147478780
runtime_loader: /boot/system/add-ons/x86/locale/catalogs/IFF: Troubles relocating: Symbol not found
}}}

I should fix this in iff_catalog (in fact I think I fixed it but did not make a new release), but it is unrelated to the issue here.

The other problem is an IO exception, possibly because LibreOffice tried to create a directory or file in a read-only place for example. It looks like on other platforms, people get a little bit more detail, the exception what() seems to be printed by std::terminate in case of uncaught exceptions, maybe? Could we add that to our version?

**Comment by Begasus** [comment] 2023-08-21 13:09
32bit version doesn't build anymore, otherwise a re-build could (maybe) fix the issue :/

**Comment by Begasus** [comment] 2023-08-23 07:07
I'm getting a different error?
```
~> /boot/system/apps/LibreOffice/LibreOffice\ Calc
--
  | ~> warn:configmgr:1086:1:configmgr/source/xcuparser.cxx:289: unknown component "org.openoffice.Office.UI.DbReportWindowState" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/registry_en-US.xcd"
  | warn:configmgr:1086:1:configmgr/source/xcuparser.cxx:289: unknown component "org.openoffice.Office.UI.ReportCommands" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/registry_en-US.xcd"
  | warn:configmgr:1086:1:configmgr/source/xcuparser.cxx:901: ignoring modify of unknown set member node "StarOffice XML (Base) Report" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/fcfg_langpack_en-US.xcd"
  | warn:configmgr:1086:1:configmgr/source/xcuparser.cxx:901: ignoring modify of unknown set member node "StarOffice XML (Base) Report Chart" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/fcfg_langpack_en-US.xcd"
  | warn:configmgr:1086:1:configmgr/source/xcuparser.cxx:901: ignoring modify of unknown set member node "SunReportBuilder" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/registry_nl.xcd"
  | warn:configmgr:1086:1:configmgr/source/xcuparser.cxx:289: unknown component "org.openoffice.Office.UI.DbReportWindowState" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/registry_nl.xcd"
  | warn:configmgr:1086:1:configmgr/source/xcuparser.cxx:289: unknown component "org.openoffice.Office.UI.ReportCommands" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/registry_nl.xcd"
  | warn:configmgr:1086:1:configmgr/source/xcuparser.cxx:901: ignoring modify of unknown set member node "com.sun.star.report.ReportDefinition" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/registry_nl.xcd"
  | warn:configmgr:1086:1:configmgr/source/xcuparser.cxx:901: ignoring modify of unknown set member node "StarOffice XML (Base) Report" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/fcfg_langpack_nl.xcd"
  | warn:configmgr:1086:1:configmgr/source/xcuparser.cxx:901: ignoring modify of unknown set member node "StarOffice XML (Base) Report Chart" in "file:///boot/system/apps/LibreOffice/program/../share/registry/res/fcfg_langpack_nl.xcd"
  | terminate called after throwing an instance of 'com::sun::star::container::NoSuchElementException'
  | terminate called recursively
  | Abort
```

**Comment by lonemadmax** [comment] 2023-08-27 18:31
Rebuilding doesn't help.

The build is fixed by adding `#include <memory>` to a few files and disabling galleries, as `gengal` crashes in a similar fashion.

I have strace output, but I don't know what to look for. It doesn't find libvclplug_gtk3lo.so and libvclplug_genlo.so, but that's at the very beginning. Also fails to get BEOS:APP_SIG from libtextencoding.so, I think:
```
[ 33302] open_dir(0xffffffff, "/boot/system/lib/x86") = 0x500000003 (70 us)
[ 33302] fcntl(0x3, F_SETFD, 0x1) = 0x4000000000 (36 us)
[ 33302] read_stat(0x3, (nil), false, 0x727f1678, 0x58) = 0x95297b5000000000 (88 us)
[ 33302] open_entry_ref(0x4, 0xd, "libtextencoding.so", 0x40, 0x1a4) = 0x4 (89 us)
[ 33302] dup(0x4) = 0x821600000005 (38 us)
[ 33302] read_stat(0x5, (nil), false, 0x727f1108, 0x58) = 0x95297b5000000000 (53 us)
[ 33302] read(0x5, 0x0, 0x727f11bc, 0x4) = 0x4000000004 (39 us)
[ 33302] read_stat(0x5, (nil), false, 0x727f10a8, 0x58) = 0x95297b5000000000 (36 us)
[ 33302] read(0x5, 0x0, 0x727f1160, 0x10) = 0x4000000010 (36 us)
[ 33302] read(0x5, 0x0, 0x727f10dc, 0x34) = 0x4000000034 (36 us)
[ 33302] read(0x5, 0x34, 0x1810b880, 0x80) = 0x4000000080 (36 us)
[ 33302] read(0x5, 0x1034bc, 0x181dda30, 0x4b0) = 0x40000004b0 (37 us)
[ 33302] read_stat(0x5, (nil), false, 0x727f1138, 0x58) = 0x95297b5000000000 (36 us)
[ 33302] read(0x5, 0x104000, 0x727f118c, 0x44) = 0x4000000044 (40 us)
[ 33302] read(0x5, 0x104044, 0x181dd290, 0x800) = 0x4000000800 (37 us)
[ 33302] read(0x5, 0x104a54, 0x181d0ad0, 0x2f) = 0x400000002f (36 us)
[ 33302] stat_attr(0x4, "BEOS:APP_SIG", 0x727f1294) = 0x80006003 No such file or directory (60 us)
[ 33302] close(0x5) = 0x4000000000 (34 us)
[ 33302] close(0x4) = 0x1b00000000 (35 us)
```

And the last lines are:
```
[ 33302] open(0xffffffff, "/boot/system/apps/LibreOffice/program/../program/libdeployment.so", 0, 0x0) = 0x50000000b (138 us)
[ 33302] normalize_path("/boot/system/apps/LibreOffice/program/../program/libdeployment.so", true, 0x727f1168) = 0x500000000 (73 us)
[ 33302] close(0xb) = 0x1400000000 (36 us)
[ 33302] open(0xffffffff, "/boot/system/apps/LibreOffice/program/../program/resource//en_US/LC_MESSAGES/dkt.mo", 0, 0x0) = 0x580006003 (73 us)
[ 33302] open(0xffffffff, "/boot/system/apps/LibreOffice/program/../program/resource//en/LC_MESSAGES/dkt.mo", 0, 0x0) = 0x580006003 (62 us)
[ 33302] resize_area(0x181a09, 0x5b30000) = 0x1700000000 (39 us)
[ 33302] access(0xffffffff, "/boot/system/data/fonts/ttfonts/NotoSansMono-Regular.ttf", 0x4, false) = 0x500000000 (88 us)
[ 33302] open(0xffffffff, "/boot/system/data/fonts/ttfonts/NotoSansMono-Regular.ttf", 0, 0x0) = 0x50000000b (71 us)
[ 33302] fcntl(0xb, F_SETFD, 0x1) = 0x0 No error (36 us)
[ 33302] read_stat(0xb, (nil), false, 0x727f06d8, 0x58) = 0x95297b5000000000 (37 us)
[ 33302] map_file("libfreetype.so.6 mmap area", [0x0], B_RANDOMIZED_ANY_ADDRESS, 0x5356c, B_READ_AREA, 0x1, true, 0xb, 0x0) = 0x00181ccd ([0x1424f000]) (98 us)
[ 33302] close(0xb) = 0x1400000000 (33 us)
[ 33302] open(0xffffffff, "/boot/system/apps/LibreOffice/program/../program/libucpexpand1lo.so", 0, 0x0) = 0x50000000b (97 us)
[ 33302] normalize_path("/boot/system/apps/LibreOffice/program/../program/libucpexpand1lo.so", true, 0x727f0f58) = 0x500000000 (70 us)
[ 33302] read(0xb, 0x0, 0x727eff24, 0x34) = 0x34 (38 us)
[ 33302] read(0xb, 0x34, 0x727eff58, 0xa0) = 0xa0 (36 us)
[ 33302] reserve_address_range([0x200000], B_RANDOMIZED_BASE_ADDRESS, 0x8000) = 0x0 No error ([0x1429000]) (61 us)
[ 33302] map_file("libucpexpand1lo.so_seg0ro", [0x1429000], B_EXACT_ADDRESS, 0x7000, B_READ_AREA|B_WRITE_AREA|B_OVERCOMMITTING_AREA, 0x1, false, 0xb, 0x0) = 0x00181cce ([0x1429000]) (89 us)
[ 33302] map_file("libucpexpand1lo.so_seg1rw", [0x1430000], B_EXACT_ADDRESS, 0x1000, B_READ_AREA|B_WRITE_AREA, 0x1, true, 0xb, 0x7000) = 0x00181ccf ([0x1430000]) (86 us)
[ 33302] read_stat(0xb, (nil), false, 0x727efe70, 0x58) = 0x95297b5000000000 (36 us)
[ 33302] register_image(0x727efa24, 0x44c) = 0x0006dceb (36 us)
[ 33302] close(0xb) = 0x1400000000 (34 us)
[ 33302] image_relocated(0x6dceb) (43 us)
[ 33302] set_area_protection(0x181cce, B_READ_AREA|B_EXECUTE_AREA) = 0x1700000000 (37 us)
[ 33302] access(0xffffffff, "/boot/system/apps/LibreOffice/program/lounorc", 0x0, false) = 0x500000000 (73 us)
[ 33302] access(0xffffffff, "/boot/system/apps/LibreOffice/program/../program/bootstraprc", 0x0, false) = 0x500000000 (63 us)
[ 33302] getuid(false) = 0x8005312d00000000 (33 us)
[ 33302] get_port_info(0x19, 0x727f0740) = 0x95297b5000000000 (35 us)
[ 33302] get_thread_info(0x8216, 0x727f0774) = 0x95297b5000000000 (34 us)
[ 33302] create_port(0x1, "KMessage reply port") = 0x00002982 (60 us)
[ 33302] set_port_owner(0x2982, 0x102) = 0x821600000000 (34 us)
[ 33302] get_thread_info(0x8216, 0x727f0694) = 0x95297b5000000000 (34 us)
[ 33302] write_port_etc(0x19, 0x4b4d5347, 0x1da82b90, 0x38, 0x0, 0x0) = 0x821600000000 (38 us)
[ 33302] get_port_message_info_etc(0x2982, 0x727f06d0, 0x10, 0x0, 0x0) = 0x95297b5000000000 (50 us)
[ 33302] read_port_etc(0x2982, [0x0], 0x1dae8700, 0x11d, 0x8, 0x0) = 0x11d0000011d (60 us)
[ 33302] delete_port(0x2982) = 0x0 No error (34 us)
[ 33302] read_stat(0xffffffff, "/boot", true, 0x727f0358, 0x58) = 0x95297b5000000000 (61 us)
[ 33302] getuid(true) = 0x8005312d00000000 (38 us)
[ 33302] open(0xffffffff, "/boot/system/apps/LibreOffice/program/../program/libucpfile1.so", 0, 0x0) = 0x50000000b (65 us)
[ 33302] normalize_path("/boot/system/apps/LibreOffice/program/../program/libucpfile1.so", true, 0x727f0da8) = 0x500000000 (65 us)
[ 33302] read(0xb, 0x0, 0x727efd74, 0x34) = 0x34 (39 us)
[ 33302] read(0xb, 0x34, 0x727efda8, 0xa0) = 0xa0 (36 us)
[ 33302] reserve_address_range([0x200000], B_RANDOMIZED_BASE_ADDRESS, 0x61000) = 0x0 No error ([0xa789000]) (85 us)
[ 33302] map_file("libucpfile1.so_seg0ro", [0xa789000], B_EXACT_ADDRESS, 0x5e000, B_READ_AREA|B_WRITE_AREA|B_OVERCOMMITTING_AREA, 0x1, false, 0xb, 0x0) = 0x00181cd0 ([0xa789000]) (91 us)
[ 33302] map_file("libucpfile1.so_seg1rw", [0xa7e7000], B_EXACT_ADDRESS, 0x3000, B_READ_AREA|B_WRITE_AREA, 0x1, true, 0xb, 0x5d000) = 0x00181cd1 ([0xa7e7000]) (86 us)
[ 33302] read_stat(0xb, (nil), true, 0x727efcc0, 0x58) = 0x95297b5000000000 (36 us)
[ 33302] register_image(0x727ef874, 0x44c) = 0x0006dcec (35 us)
[ 33302] close(0xb) = 0x1400000000 (34 us)
[ 33302] image_relocated(0x6dcec) (43 us)
[ 33302] set_area_protection(0x181cd0, B_READ_AREA|B_EXECUTE_AREA) = 0x1700000000 (44 us)
[ 33302] open(0xffffffff, "/boot/system/apps/LibreOffice/program/../program/libucb1.so", 0, 0x0) = 0x50000000b (81 us)
[ 33302] normalize_path("/boot/system/apps/LibreOffice/program/../program/libucb1.so", true, 0x727f0dd8) = 0x500000000 (66 us)
[ 33302] close(0xb) = 0x1400000000 (35 us)
[ 33302] access(0xffffffff, "/boot/home/config/settings/LibreOffice/4/user/extensions/shared/registry", 0x0, false) = 0x580006003 (77 us)
[ 33302] access(0xffffffff, "/boot/home/config/settings/LibreOffice/4/user/extensions/shared/registry", 0x0, false) = 0x580006003 (63 us)
[ 33302] open(0xffffffff, "/dev/urandom", 0, 0x0) = 0x50000000b (72 us)
[ 33302] read(0xb, 0xffffffffffffffff, 0x1814d00, 0x10) = 0x10 (116 us)
[ 33302] close(0xb) = 0x1400000000 (34 us)
[ 33302] map_file("libuno_sal.so.3 mmap area", [0x0], B_RANDOMIZED_ANY_ADDRESS, 0x10000, B_READ_AREA|B_WRITE_AREA, 0x1, true, 0xffffffff, 0x0) = 0x00181cd2 ([0x143e2000]) (93 us)
[ 33302] map_file("libgcc3_uno.so mmap area", [0x0], B_RANDOMIZED_ANY_ADDRESS, 0x1000, B_READ_AREA|B_WRITE_AREA, 0x1, true, 0xffffffff, 0x0) = 0x00181cd3 ([0x14a37000]) (86 us)
[ 33302] set_memory_protection(0x14a37000, 0x1000, B_READ_AREA|B_WRITE_AREA|B_EXECUTE_AREA) = 0x821600000000 (37 us)
[ 33302] write(0x2, 0xffffffffffffffff, 0x16957ac, 0x30) = 0x80200000030 (135 us)
[ 33302] write(0x2, 0xffffffffffffffff, 0x1daf4270, 0x34) = 0x80200000034 (102 us)
[ 33302] write(0x2, 0xffffffffffffffff, 0x169860d, 0x2) = 0x80200000002 (45 us)
[ 33302] write(0x2, 0xffffffffffffffff, 0x1697319, 0x6) = 0x80200000006 (40 us)
[ 33302] sigaction(0x6, (nil), 0x727f190c) = 0x95297b5000000000 (36 us)
[ 33302] send_signal(0x8216, 0x6, (nil), 0x20000) = 0x100000000 (37 us)
[ 33302] --- SIGABRT (Abort) {si_signo=SIGABRT, si_code=SI_USER, si_pid=33302, si_uid=0, si_value=(nil)} ---
[ 33302] mutex_unblock(0x1d57fc30 [B_USER_MUTEX_WAITING], 0x80000000) = 0xe986a12800000000 (65 us)
[ 33302] wait_for_thread(0x821b, [0x160f962]) <unfinished ...>
[ 33307] <... mutex_switch_lock resumed>  = 0x0 No error (383662 us)
[ 33307] create_dir(0xffffffff, "/boot/home/config/settings/LibreOffice/4/user", 0x1ed) = 0x380006002 (156 us)
[ 33307] open(0xffffffff, "/boot/home/config/settings/LibreOffice/4/user/SrCrJC", O_RDWR|O_EXCL|O_CREAT, 0x180) = 0x30000000b (395 us)
[ 33307] read_stat(0xb, (nil), false, 0x7ab6a824, 0x58) = 0x9529185000000000 (62 us)
[ 33307] read(0xb, 0x0, 0x1db99890, 0x1000) = 0x30200000000 (138 us)
[ 33307] write(0xb, 0x0, 0x1db99890, 0x402) = 0x30200000402 (254 us)
[ 33307] close(0xb) = 0xe00000000 (245 us)
[ 33307] rename(0xffffffff, "/boot/home/config/settings/LibreOffice/4/user/SrCrJC", 0xffffffff, "/boot/home/config/settings/LibreOffice/4/user/registrymodifications.xcu") = 0x300000000 (361 us)
[ 33307] exit_thread(0x0) (51 us)
[ 33302] <... wait_for_thread resumed>  = 0x95297b5000000000 (2502 us)
[ 33302] read_stat(0xffffffff, "/boot/home/config/settings/LibreOffice/4/.lock", false, 0x727f0f44, 0x58) = 0x95297b5000000000 (94 us)
[ 33302] unlink(0xffffffff, "/boot/home/config/settings/LibreOffice/4/.lock") = 0x500000000 (169 us)
[ 33302] write(0x2, 0xffffffffffffffff, 0x5225fb2, 0x12) = 0x80200000012 (48 us)
[ 33302] exit_team(0x1) (36 us)
```

**Comment by unspacyar** [comment] 2023-09-07 23:45
Hello.  Taking into consideration that the LibreOffice package got broken because changes in other package, could be useful if I try to isoltate wich packages were modified between hrev57184 and hrev57246 ?

**Comment by lonemadmax** [comment] 2023-09-12 19:23
> wich packages were modified between hrev57184 and hrev57246 ?

We can reduce that a bit. Works in hrev57197 and doesn't work in hrev57199, the one with the new gcc. LibreOffice still works (or at least it opens a window instead of crashing, I didn't test any further) after updating so that we have the same packages except the haiku ones and gcc_x86_syslibs. Update gcc_x86_syslibs and it crashes.

I'll try rebuilding the 100+ dependencies under gcc 13 and see if there's any luck with that.

**Comment by lonemadmax** [comment] 2023-10-02 18:09
> I'll try rebuilding the 100+ dependencies under gcc 13 and see if there's any luck with that.

No luck. I even tried with 7.3.7.2 (was it not for this issue, it's just a path change away from activation for 32 bit), same crash in `gengal` while building and same error on start when built without galleries.

**Comment by kenmays** [comment] 2023-10-06 13:26
Patch issue. LibreOffice 6.4.7.2-10 build on hrev57305 x86 result:
```
Applying: Fix KF5 detection
Applying patch "/boot/home/haikuports/app-office/libreoffice/patches/MissingHeader.patch" ...
error: patch failed: chart2/source/view/inc/PlottingPositionHelper.hxx:18
error: chart2/source/view/inc/PlottingPositionHelper.hxx: patch does not apply
error: patch failed: connectivity/source/inc/java/tools.hxx:19
error: connectivity/source/inc/java/tools.hxx: patch does not apply
error: patch failed: filter/source/xsltdialog/xmlfilterjar.hxx:22
error: filter/source/xsltdialog/xmlfilterjar.hxx: patch does not apply
error: patch failed: forms/source/xforms/propertysetbase.hxx:26
error: forms/source/xforms/propertysetbase.hxx: patch does not apply
error: patch failed: fpicker/source/office/contentenumeration.hxx:19
error: fpicker/source/office/contentenumeration.hxx: patch does not apply
error: include/oox/crypto/StrongEncryptionDataSpace.hxx: does not exist in index
error: patch failed: include/sfx2/sidebar/SidebarPanelBase.hxx:18
error: include/sfx2/sidebar/SidebarPanelBase.hxx: patch does not apply
error: patch failed: include/svtools/imageresourceaccess.hxx:19
error: include/svtools/imageresourceaccess.hxx: patch does not apply
error: patch failed: starmath/inc/token.hxx:35
error: starmath/inc/token.hxx: patch does not apply
error: patch failed: svx/source/unodialogs/textconversiondlgs/chinese_translation_unodialog.hxx:19
error: svx/source/unodialogs/textconversiondlgs/chinese_translation_unodialog.hxx: patch does not apply
error: patch failed: sw/source/uibase/docvw/ShadowOverlayObject.hxx:19
error: sw/source/uibase/docvw/ShadowOverlayObject.hxx: patch does not apply
error: patch failed: xmlsecurity/source/gpg/SecurityEnvironment.hxx:10
error: xmlsecurity/source/gpg/SecurityEnvironment.hxx: patch does not apply
error: patch failed: xmlsecurity/source/helper/ooxmlsecparser.hxx:16
error: xmlsecurity/source/helper/ooxmlsecparser.hxx: patch does not apply
error: patch failed: xmlsecurity/source/helper/xsecparser.hxx:26
error: xmlsecurity/source/helper/xsecparser.hxx: patch does not apply
HEAD is now at 906a4ef import
Removing dictionaries/

```

**Comment by lonemadmax** [comment] 2023-10-06 14:47
Which is known, as you can read in the comments from the latest patch:

> Was worth the shot, but seems the patch is too new for old LO 6.4 :-D (build failed with "error: patch failed").

and in this same issue:

> 32bit version doesn't build anymore, otherwise a re-build could (maybe) fix the issue :/

> The build is fixed by adding #include \<memory\> to a few files and disabling galleries, as `gengal` crashes in a similar fashion.

And before you do that, it's not worth it if all you'll come to is that rebuilding still doesn't solve the issue, as that is also known. We need someone that can guess why the gcc_x86_syslibs update breaks LO or, if this is a bug in LO that's been solved in a more up to date version, someone that builds and tests that.

**Comment by waddlesplash** [comment] 2023-11-01 03:50
Probably related: Koder crashes on startup with an exception that should be caught by a try-catch block, see https://github.com/KapiX/Koder/issues/147. Also crashes on 32-bit and works on 64-bit. Maybe that would be easier to investigate?

**Comment by korli** [comment] 2024-06-13 09:21
Please consider rebuilding with a fixed GCC 13 on x86.

**Comment by korli** [comment] 2024-09-04 08:47
Please check with 6.4.7.2-15

**Comment by unspacyar** [comment] 2024-09-09 05:07
Hi @korli ! I confirm that with version 6.4.7.2-15 the issue was fixed on Haiku 32 bit (tested on nightly hrev58057).
The ticket can be closed.  Thank you!!!! :-)

**Closed** 2024-09-09 06:41 UTC
Labels: type-bug
