### ISSUE TITLE
Infinite loop trying to run/install pip

### ISSUE THREAD

**Issue by probonopd** [haikuports/haikuports#3991] opened 2019-07-15 13:43 UTC
```
~> pip install zeroconf
DEBUG:__main__:Entered CNF: pip
This application is aviaiblible via pkgman install pip

~>  pkgman install pip
100% repochecksum-1 [65 bytes]
Validating checksum for BeSly Software Solutions...done.
100% repochecksum-1 [65 bytes]
Validating checksum for Haiku...done.
100% repochecksum-1 [64 bytes]
Validating checksum for HaikuPorts...done.
pip-9.0.0-1 from repository system is already installed.
Nothing to do.

~> pip install zeroconf
DEBUG:__main__:Entered CNF: pip
This application is aviaiblible via pkgman install pip
```

**Comment by probonopd** [comment] 2019-07-15 13:45
`pip3` fails too, but in a different way:

```
~> pip3
DEBUG:__main__:Entered CNF: pip3
This application is aviaiblible via pkgman install pip3

~> pkgman install pip3
100% repochecksum-1 [65 bytes]
Validating checksum for Haiku...done.
100% repochecksum-1 [64 bytes]
Validating checksum for HaikuPorts...done.
*** Failed to find a match for "pip3": Name not found
```

**Comment by probonopd** [comment] 2019-07-15 13:47
This works:

```
~>  pkgman install pip_python
~>  pkgman install pip_python3
```

Now I have `pip` and `pip3`. Actually `cnf` was misleading here! Why?

**Comment by diversys** [comment] 2019-07-15 13:54
The following messages
```
DEBUG:__main__:Entered CNF: pip
This application is aviaiblible via pkgman install pip
```

come from `command_not_found` package. It looks like it is somewhat broken.

**Comment by pulkomandy** [comment] 2019-07-15 14:08
Duplicate of #3923

**Closed by pulkomandy** 2019-07-15 14:08 UTC
