### ISSUE TITLE
numpy: crash on import (regression)

### ISSUE THREAD

**Issue by iam-git** [haikuports/haikuports#5624] opened 2021-01-23 01:01 UTC
numpy 1.19.4-1
Crash just on import:
`~> python3
Python 3.7.9 (default, Oct 27 2020, 19:19:35) 
[GCC 8.3.0] on haiku1
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Kill Thread
`

Debug information for team /boot/system/bin/python3.7m (3450):
CPU(s): 4x Intel Core i5
Memory: 3.80 GiB total, 1.20 GiB used
Haiku revision: hrev54905 Jan 22 2021 08:19:20 (x86_64)

Active Threads:
	thread 3454: team 3450 debug task 
	thread 3450: python3 (main)
		state: Exception (Segment violation)

**Comment by iam-git** [comment] 2021-01-24 00:44
fallback to previous version of numpy doesn't help(

**Comment by extrowerk** [comment] 2021-01-25 04:39
I tried to find the culprit earlier, rebuilt numpy with disabling their deps one-by-one but i was unable to find whats the problem is.
I think it is openblas, but i am not sure. More detective-work needed.

**Comment by extrowerk** [comment] 2021-01-26 12:07
Related https://github.com/haikuports/haikuports/issues/5599

**Comment by iam-git** [comment] 2021-01-29 08:08
At least previous numpy works for me with previous openblas version.

**Comment by Begasus** [comment] 2021-02-05 17:32
Could you check if latest bump to numpy fixed it? https://github.com/haikuports/haikuports/pull/5647

**Comment by Begasus** [comment] 2021-02-07 12:58
Seems to be ok here (typing numpy after help() shows me the file for numpy)?
```
~> python3.8
Python 3.8.7 (default, Jan 15 2021, 23:18:50) 
[GCC 8.3.0] on haiku1
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> help()

Welcome to Python 3.8's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.8/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> numpy

help> 
You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.
>>> 
~>
```

**Comment by korli** [comment] 2021-06-14 08:50
@Begasus is it fixed with 1eb5ff866e8dc8e3b70ac149211990778bebbfbe ?

**Comment by Begasus** [comment] 2021-06-14 17:05
> I think it is openblas, but i am not sure.

I know the openblas latest bump is ok on 32bit but failed on 64bit on the buildbot, maybe related as @extrowerk suggested?

**Comment by extrowerk** [comment] 2021-06-15 03:05
> > I think it is openblas, but i am not sure.
> 
> I know the openblas latest bump is ok on 32bit but failed on 64bit on the buildbot, maybe related as @extrowerk suggested?

I dont know, possible.

**Comment by Begasus** [comment] 2021-06-17 13:45
I think this can be closed (report if someone still has issues)
Ran `~/python3` ... `import numpy` ... `help()` ... `numpy` (works ok for python3.8,  python3.9 too)

```
Help on package numpy:

NAME
    numpy

MODULE REFERENCE
    https://docs.python.org/3.7/library/numpy
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    NumPy
    =====
    
    Provides
      1. An array object of arbitrary homogeneous items
      2. Fast mathematical operations over arrays
      3. Linear Algebra, Fourier Transforms, Random Number Generation
```

**Comment by Begasus** [comment] 2021-06-19 07:09
OK, just checked, on 32bit it seems to be fine, on 64bit it crashes for python3, doesn't seem to find it for python3.8 and for python3.9 it crashes too :(

**Comment by iam-git** [comment] 2021-08-28 11:32
I need to say, numpy works fine for me on the latest x86_64 Haiku

**Comment by iam-git** [comment] 2021-08-28 16:20
I'm in doubt now. I'd rather check what exactly numpy&openBLAS versions I have installed. I'll drop a message when I get to PC.

**Comment by iam-git** [comment] 2021-08-30 12:14
openblas 0.3.17-4 and numpy 1.20.3-1 work fine on hrev55318 x86_64.

**Comment by iam-git** [comment] 2021-09-11 07:03
Don't really feel the issue as mine, but probably it is really time to close it.

**Closed** 2021-09-11 07:04 UTC
Labels: type-bug
