### ISSUE TITLE
tk_devel contains X11 headers conflicting with xlibe and xorgproto

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#7501] opened 2022-11-29 20:37 UTC
When having tk_devel installed, using xlibe fails. tk_devel contains some X11 headers (including Xlib.h and Xfuncproto.h).

On my system, there is now Xlib.h visible from xlibe_devel and Xfuncproto.h from tk_devel. This causes compile errors because Xlib.h uses `_X_DEPRECATED` and `_X_SENTINEL` which should be defined in Xfuncproto.h, but they aren't in Tk's version of it.

Just including <X11/Xlib.h> causes the following errors:

```
/boot/system/develop/headers/X11/Xlib.h:1686:1: error: '_X_DEPRECATED' does not name a type
 1686 | _X_DEPRECATED
      | ^~~~~~~~~~~~~
/boot/system/develop/headers/X11/Xlib.h:3571:3: error: expected initializer before '_X_SENTINEL'
 3571 | ) _X_SENTINEL(0);
      |   ^~~~~~~~~~~
/boot/system/develop/headers/X11/Xlib.h:3576:3: error: expected initializer before '_X_SENTINEL'
 3576 | ) _X_SENTINEL(0);
      |   ^~~~~~~~~~~
/boot/system/develop/headers/X11/Xlib.h:3589:3: error: expected initializer before '_X_SENTINEL'
 3589 | ) _X_SENTINEL(0);
      |   ^~~~~~~~~~~
/boot/system/develop/headers/X11/Xlib.h:3602:3: error: expected initializer before '_X_SENTINEL'
 3602 | ) _X_SENTINEL(0);
      |   ^~~~~~~~~~~
/boot/system/develop/headers/X11/Xlib.h:3607:3: error: expected initializer before '_X_SENTINEL'
 3607 | ) _X_SENTINEL(0);
      |   ^~~~~~~~~~~
/boot/system/develop/headers/X11/Xlib.h:3839:3: error: expected initializer before '_X_SENTINEL'
 3839 | ) _X_SENTINEL(0);
      |   ^~~~~~~~~~~
/boot/system/develop/headers/X11/Xlib.h:3843:3: error: expected initializer before '_X_SENTINEL'
 3843 | ) _X_SENTINEL(0);
      |   ^~~~~~~~~~~
/boot/system/develop/headers/X11/Xlib.h:3855:3: error: expected initializer before '_X_SENTINEL'
 3855 | ) _X_SENTINEL(0);
      |   ^~~~~~~~~~~
/boot/system/develop/headers/X11/Xlib.h:3883:3: error: expected initializer before '_X_SENTINEL'
 3883 | ) _X_SENTINEL(0);
      |   ^~~~~~~~~~~
/boot/system/develop/headers/X11/Xlib.h:3887:3: error: expected initializer before '_X_SENTINEL'
 3887 | ) _X_SENTINEL(0);
      |   ^~~~~~~~~~~
/boot/system/develop/headers/X11/Xlib.h:3927:3: error: expected initializer before '_X_SENTINEL'
 3927 | ) _X_SENTINEL(0);
      |   ^~~~~~~~~~~
```

The X11 headers should be removed from tk_devel (they are not part of tk-devel on OpenSUSE either).

**Comment by waddlesplash** [comment] 2022-11-29 21:19
They're part of tk_devel because Tk provides its own (partial) implementation of X11/Xlib. Presumably on OpenSUSE it uses the real system one. It doesn't use Xlibe at present because there's a bunch of serious redraw errors which I didn't manage to determine the cause of.

Likely the tk_devel package should just CONFLICTS with xlibe, until that's all fixed.

**Comment by jmairboeck** [comment] 2022-11-30 15:04
The official version of Tk 8.6.13 contains a more modern set of X11 headers, including the missing symbols. I noticed because I just updated to it at work, and the Windows version also installs the X11 headers.

But it seems that the SDL-Tk in Androwish is still based on version 8.6.10 ...

**Comment by Begasus** [comment] 2023-05-12 17:16
Same error when trying to build tuxpaint-config when tk_devel is installed.

**Comment by Begasus** [comment] 2023-06-11 06:20
This is fixed by adding a conflict between both devel packages.

**Closed by Begasus** 2023-06-11 06:20 UTC
Labels: type-bug
