### ISSUE TITLE
ZSH: scripts with shebang - script file path not expanded (Haiku Beta1 x86_64)

### ISSUE THREAD

**Issue by vegardw** [haikuports/haikuports#3920] opened 2019-06-10 15:11 UTC
When using zsh as the shell, running script files with a shebang line fails due to the full path to the script file not being expanded before calling the interpreter

### Steps to reproduce

create the following file as `/boot/home/config/non-packaged/bin/test.py` and make it executable:
```
#!/usr/bin/env python
import sys
print sys.argv[0]
```
Then execute with `test.py` from `/boot/home`:
```
test.py
```

### Expected results
When running the script the script, it should print the following line, as it does when using bash as the shell:
```
/boot/home/config/non-packaged/bin/test.py
```

### Actual result
When running `test.py` with zsh as the shell, the following error is printed instead:
```
python: can't open file 'test.py': [Errno -2147459069] No such file or directory
```
Here we see that `/bin/env python test.py` is executed instead of `/bin/env python /boot/home/config/non-packaged/bin/test.py`, as should be executed. This fails since the current working directory is `/boot/home`

### Tested on
Haiku beta 1 x86_64, up-to-date using pkgman, zsh installed using `pkgman install zsh`:
```
~> date
Mon Jun 10 17:09:07 GMT+2 2019
~> pkgman full-sync
100% repochecksum-1 [65 bytes]
Validating checksum for Haiku...done.
100% repochecksum-1 [64 bytes]
Validating checksum for HaikuPorts...done.
Nothing to do.
~> pkgman search zsh | grep '^S'
Status  Name                      Description                                                                          
S       zsh                       A very advanced and programmable command interpreter (shell) for UNIX                
~> uname -a
Haiku haiku-beta1-x64 1 hrev52295+129 Mar  4 2019 10:03 x86_64 x86_64 Haiku
~> zsh --version
zsh 5.7.1 (x86_64-unknown-haiku)

```

**Comment by augiedoggie** [comment] 2022-01-29 16:22
I'm unable to reproduce this problem with zsh 5.8 and python 2.7.18 and 3.8.  Perhaps it was fixed by some update.

**Comment by augiedoggie** [comment] 2024-12-13 04:25
No response

**Closed by augiedoggie** 2024-12-13 04:25 UTC
Labels: type-bug
