### ISSUE TITLE
pip3: ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by probonopd** [haikuports/haikuports#3992] opened 2019-07-15 13:48 UTC
```
~> pip3 install zeroconf
Traceback (most recent call last):
  File "/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by Begasus** [comment] 2019-08-12 05:09
Duplicate of https://github.com/haikuports/haikuports/issues/3923

**Closed by Begasus** 2019-08-12 05:09 UTC
