### ISSUE TITLE
Web (Epiphany) ignores system keymap setting

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#7524] opened 2022-12-06 16:28 UTC
My system runs with English as language and a German keymap. Web (Epipany) seems to use an English keymap.

("Add language" in the preferences opens an empty list window. Sometimes click on "Add language" crashes the app. I experimentally removed the English language and don't get it back...)

**Comment by korli** [comment] 2022-12-07 08:14
if this needs to be fixed in Haiku, a bug report would be nice (eventually with a small test case). Otherwise using  StringBuffer/mkstemp/mmap like other platforms might do.

**Comment by waddlesplash** [comment] 2022-12-07 18:02
Note that `ramfs` has a very large "optimal IO size". If using `FILE*`, changes may not be flushed until closing the file or the size is reached. Perhaps that may be happening here?

It's also possible this is a ramfs bug, would be good to get a reproducer...

**Comment by waddlesplash** [comment] 2022-12-07 19:04
OK, it seems this is indeed a ramfs bug: unlinked files can't be written to.

**Comment by waddlesplash** [comment] 2022-12-07 19:08
Or, actually, they can be written to, but they don't have a stat entry so `stat` just fails. Guess if other FSes have that work anyway, we should make it work for ramfs.

**Comment by waddlesplash** [comment] 2022-12-07 19:10
```
[304970] open(0xffffffff, "/var/shared_memory/wayland-AKfMJc", 0x303, 0x180) = 0x3 () (127 us)
[304970] unlink(0xffffffff, "/var/shared_memory/wayland-AKfMJc") = 0x0 No error () (108 us)
[304970] dup(0x3) = 0x4 () (45 us)
[304970] fcntl(0x4, F_GETFL, 0x1c4628e782d) = 0x303 No Error (771) () (68 us)
[304970] read_stat(0x4, (nil), false, 0x7f59953dc200, 0x80) = 0x0 No error () (45 us)
[304970] seek(0x4, 0x0, 0x1) = 0x0 () (43 us)
[304970] write(0x4, 0xffffffffffffffff, 0x11427d701b60, 0x2000) = 0xffffffff80006000 () (45 us)
[304970] write(0x4, 0xffffffffffffffff, 0x11427d701b60, 0x2000) = 0xffffffff80006000 () (41 us)
[304970] write(0x4, 0xffffffffffffffff, 0x11427d701b60, 0x19e1) = 0xffffffff80006000 () (50 us)
[304970] close(0x4) = 0x0 No error () (23 us)
```
clearly the FD still exists because we can `close` it but `write` produces "Bad file descriptor". Strange.

**Comment by waddlesplash** [comment] 2022-12-07 23:00
fixed by hrev56629, +beta4.

**Closed** 2022-12-10 01:14 UTC
Labels: type-enhancement
